# -*- coding: utf-8 -*-
"""LOT G - Exercices gamifies : une technique de gamification par exercice."""

LOT_G = [

dict(id="G-01", titre="Le tableau des scores", them="G1 · Progression et récompense",
 ref="REF-047, REF-043", niv="Débutant", duree=10, prereq="A-10",
 obj="Rendre visible la performance immédiate de l'apprenant sur une tâche de tri.",
 tech="Score visible et barème explicite (scoreboard)",
 comp="Series, Sort List, Panel, Mass Addition, Value Tracker (Human)",
 enonce="Trie les 12 valeurs par ordre croissant. Chaque valeur correctement placée rapporte 10 points, chaque valeur mal placée en coûte 5. Le score s'affiche en direct dans le panneau SCORE.",
 depart="Une liste de 12 nombres mélangés et un groupe SCORE pré-câblé.",
 att="Liste triée et score final de 120 points.",
 mode="ExactOrderedList", tol="0", nb=8,
 impl="Magpie compare la proposition à la solution élément par élément et calcule le score par la formule 10×justes − 5×faux. Le score est renvoyé au plugin comme métrique secondaire et affiché en temps réel dans le panneau de l'exercice.",
 etapes=["Poser Sort List sur la liste fournie.",
         "Brancher la sortie sur le paramètre de réponse attendu par Magpie.",
         "Le groupe SCORE compare position par position et cumule les points.",
         "Le score atteint 120 lorsque les 12 valeurs sont bien placées."],
 pieges=["Trier une copie de la liste sans la rebrancher sur le paramètre de réponse.",
         "Score partiel accepté comme réussite : le seuil de validation reste à 100 %."],
 var=["Introduire un malus de temps.", "Afficher un score cumulé sur tout le parcours."],
 bareme="120 points maximum, validation à 120."),

dict(id="G-02", titre="La barre de progression", them="G1 · Progression et récompense",
 ref="REF-062, REF-063", niv="Débutant", duree=12, prereq="A-34",
 obj="Découper une tâche en jalons visibles pour soutenir l'effort.",
 tech="Barre de progression et jalons intermédiaires",
 comp="Circle, Rectangle, Polygon, Line, Boolean Toggle, Gradient",
 enonce="Reconstitue le logo en 5 étapes. Chaque forme correctement placée fait progresser la barre de 20 %. La barre passe au vert à 100 %.",
 depart="Un gabarit du logo en filigrane et une barre de progression pré-câblée.",
 att="Les 5 formes placées, barre à 100 %.",
 mode="GeometryTolerance", tol="0,5 mm", nb=14,
 impl="Magpie évalue 5 sous-critères indépendants. Le taux de réussite partiel pilote la largeur d'un rectangle de progression dessiné sur le canvas et sa couleur via un Gradient.",
 etapes=["Identifier les 5 formes du gabarit : cercle, rectangle, triangle, hexagone, segment.",
         "Construire chaque forme avec le composant natif adapté.",
         "Positionner chaque forme sur son repère.",
         "Brancher chaque forme sur l'entrée correspondante du groupe de contrôle.",
         "Observer la barre progresser à chaque forme validée."],
 pieges=["Formes correctes mais mal positionnées : le sous-critère reste rouge.",
         "Brancher toutes les formes sur une seule entrée."],
 var=["Barre segmentée par chapitre.", "Ajouter un pourcentage chiffré."],
 bareme="20 % par forme, validation à 100 %."),

dict(id="G-03", titre="Contre la montre", them="G1 · Progression et récompense",
 ref="REF-042, REF-043", niv="Intermédiaire", duree=6, prereq="A-11, A-12",
 obj="Travailler la vitesse d'exécution sur des gestes déjà maîtrisés.",
 tech="Compte à rebours et mode time attack",
 comp="List Item, List Length, Sub List, Panel, Timer",
 enonce="Cinq extractions de listes à réaliser en moins de 180 secondes. Le chronomètre démarre à l'ouverture de l'exercice et s'affiche en haut du canvas.",
 depart="Cinq listes internalisées et cinq paramètres de réponse.",
 att="Les cinq extractions correctes dans le temps imparti.",
 mode="ExactOrderedList", tol="0", nb=12,
 impl="Magpie exploite la métrique de durée déjà collectée par le plugin et la compare à une durée cible stockée dans le JSON de l'exercice. Au-delà, l'exercice reste validable mais sans le bonus de temps.",
 etapes=["Lire les cinq consignes affichées dans le Scribble.",
         "Traiter chaque liste avec le composant adapté sans chercher l'élégance.",
         "Brancher les cinq réponses.",
         "Valider avant la fin du compte à rebours."],
 pieges=["Perdre du temps à ranger le canvas au lieu de répondre.",
         "Réponse correcte soumise après l'échéance : la validation reste acquise, le bonus est perdu."],
 var=["Mode survie où chaque erreur retire 15 secondes.", "Classement des temps entre apprenants."],
 bareme="5 points, plus 3 points de bonus si le temps cible est tenu."),

dict(id="G-04", titre="Trois vies", them="G1 · Progression et récompense",
 ref="REF-053, REF-054", niv="Intermédiaire", duree=15, prereq="A-24, A-25",
 obj="Inciter à réfléchir avant de soumettre, en limitant le nombre de tentatives.",
 tech="Système de vies et tentatives limitées",
 comp="Longest List, Cross Reference, Addition, List Length, Panel",
 enonce="Trois questions sur les modes de correspondance de données. Tu disposes de trois vies : chaque mauvaise soumission en coûte une. À zéro vie, l'exercice se recharge depuis le début.",
 depart="Deux listes de tailles différentes et trois paramètres de réponse.",
 att="Les trois réponses correctes avec au moins une vie restante.",
 mode="SingleValue", tol="0", nb=10,
 impl="Magpie utilise la métrique du nombre de tentatives. Au-delà de trois soumissions infructueuses, le plugin déclenche le rechargement de l'exercice et remet le compteur à zéro.",
 etapes=["Déterminer par le raisonnement le nombre de résultats attendus dans chaque mode.",
         "Vérifier mentalement avant de brancher.",
         "Soumettre les trois réponses en une seule validation.",
         "Utiliser les vies restantes comme indicateur de maîtrise."],
 pieges=["Soumettre par essais successifs : les vies s'épuisent en trois coups.",
         "Confondre Longest List et Cross Reference."],
 var=["Vies régénérées par une bonne réponse d'affilée.", "Mode sans faute avec une seule vie."],
 bareme="3 points, moins 1 point par vie perdue."),

dict(id="G-05", titre="La collection de badges", them="G1 · Progression et récompense",
 ref="REF-079, REF-081, REF-098", niv="Intermédiaire", duree=20, prereq="A-47, A-49",
 obj="Valoriser la maîtrise d'une famille complète de composants.",
 tech="Badges et trophées par compétence",
 comp="Length, Area, Volume, Point, Bounding Box, Text Tag 3D",
 enonce="Six mesures à produire sur le même assemblage. Chaque mesure exacte débloque un badge. La collection complète débloque le badge doré ARPENTEUR.",
 depart="Un assemblage internalisé et six paramètres de réponse.",
 att="Les six mesures exactes et le badge doré.",
 mode="NumericTolerance", tol="0,5 %", nb=16,
 impl="Chaque sous-critère validé écrit un identifiant de badge dans le résultat du parcours. Le plugin agrège les badges au niveau du parcours et les fait figurer sur le certificat PDF.",
 etapes=["Mesurer le développé des arêtes avec Length et Mass Addition.",
         "Mesurer la surface totale avec Area.",
         "Mesurer le volume avec Volume.",
         "Localiser le centre de gravité avec la sortie C de Volume.",
         "Mesurer l'encombrement avec Bounding Box et Deconstruct Box.",
         "Compter les faces avec Deconstruct Brep et List Length."],
 pieges=["Mesurer la surface d'une face au lieu de la surface totale.",
         "Encombrement mesuré dans un repère tourné."],
 var=["Badges de rareté selon le nombre de tentatives.", "Badge secret pour une solution en moins de 12 composants."],
 bareme="1 point par badge, badge doré à 6/6."),

dict(id="G-06", titre="Le déblocage progressif", them="G1 · Progression et récompense",
 ref="REF-059, REF-060, REF-061", niv="Intermédiaire", duree=18, prereq="A-29, A-30, A-31",
 obj="Enchaîner des difficultés croissantes, chaque niveau ouvrant l'accès au suivant.",
 tech="Niveaux et déblocage séquentiel (unlock)",
 comp="Equality, Larger Than, Gate And, Gate Or, Stream Filter, Dispatch",
 enonce="Trois niveaux de logique. Le niveau 2 ne devient actif qu'une fois le niveau 1 validé, et ainsi de suite. Les groupes verrouillés apparaissent grisés.",
 depart="Trois groupes de travail dont deux verrouillés.",
 att="Les trois niveaux validés successivement.",
 mode="SetEquality", tol="0", nb=18,
 impl="Le parcours Magpie enchaîne trois exercices distincts avec un seuil de réussite par étape. Le bouton Suivant reste inactif tant que l'étape courante n'est pas validée, comportement déjà présent dans le prototype.",
 etapes=["Niveau 1 : produire un booléen unique par comparaison.",
         "Niveau 2 : combiner deux conditions par Gate And.",
         "Niveau 3 : orienter un flux géométrique selon la condition combinée.",
         "Valider chaque niveau avant de passer au suivant."],
 pieges=["Tenter de câbler le niveau 3 avant validation du niveau 1.",
         "Réutiliser un booléen d'un niveau antérieur devenu obsolète."],
 var=["Déblocage d'un niveau bonus caché.", "Retour possible sur un niveau validé pour améliorer son score."],
 bareme="3 points, 1 par niveau."),

dict(id="G-07", titre="Une, deux ou trois étoiles", them="G1 · Progression et récompense",
 ref="REF-067, REF-068", niv="Intermédiaire", duree=15, prereq="A-39",
 obj="Distinguer la simple réussite de la réussite élégante.",
 tech="Notation par étoiles selon la qualité de la solution",
 comp="Rectangular Array, Polar Array, Move, Series, Graft",
 enonce="Produis la trame demandée. Une étoile pour un résultat juste, deux étoiles si la solution tient en moins de 12 composants, trois étoiles si elle reste juste après changement des paramètres de trame.",
 depart="Un module et une trame cible affichée en filigrane.",
 att="La trame produite, idéalement en moins de 12 composants et paramétrique.",
 mode="GeometryTolerance", tol="0,5 mm", nb=9,
 impl="Magpie exploite deux métriques déjà disponibles : le nombre de composants et l'écart au chemin attendu. Une troisième vérification relance la comparaison avec un second jeu de paramètres pour tester la robustesse.",
 etapes=["Analyser la trame cible : nombre de rangs, nombre de colonnes, entraxes.",
         "Choisir Rectangular Array plutôt qu'une suite de Move.",
         "Paramétrer les entraxes par des sliders et non par des valeurs codées en dur.",
         "Vérifier que le résultat reste juste après modification des sliders."],
 pieges=["Placer les modules un par un : le résultat est juste mais coûte 40 composants.",
         "Coder les entraxes en dur : la troisième étoile est perdue."],
 var=["Étoile bonus pour une solution sans Graft.", "Comparatif des solutions de la promotion."],
 bareme="3 étoiles, validation dès la première."),

dict(id="G-08", titre="La série de bonnes réponses", them="G1 · Progression et récompense",
 ref="REF-044, REF-045, REF-046", niv="Intermédiaire", duree=16, prereq="A-13, A-14, A-16",
 obj="Récompenser la régularité plutôt que le coup de chance.",
 tech="Combo et multiplicateur de série (streak)",
 comp="Sort List, Cull Pattern, Shift List, Reverse List, Panel",
 enonce="Huit manipulations de listes s'enchaînent. Chaque bonne réponse consécutive augmente le multiplicateur : ×1, ×1,5, ×2, ×3. Une erreur remet le multiplicateur à ×1.",
 depart="Huit listes internalisées et huit paramètres de réponse.",
 att="Les huit réponses correctes, multiplicateur maximal atteint.",
 mode="ExactOrderedList", tol="0", nb=20,
 impl="Le parcours Magpie enchaîne huit micro-exercices. Le plugin conserve l'état de la série entre exercices et applique le multiplicateur au score du parcours.",
 etapes=["Traiter les huit consignes dans l'ordre imposé par le Scribble.",
         "Vérifier chaque résultat dans un Panel avant de brancher la réponse.",
         "Ne soumettre qu'une fois l'ensemble contrôlé.",
         "Observer le multiplicateur monter dans le panneau de score."],
 pieges=["Traiter les listes dans le désordre : la série se casse.",
         "Confondre Cull Pattern et Cull Index sur la manipulation 4."],
 var=["Série conservée d'une session à l'autre.", "Bonus de série sur toute une thématique."],
 bareme="8 points de base, jusqu'à 24 points avec multiplicateur."),

dict(id="G-09", titre="Le composant caché", them="G2 · Exploration et découverte",
 ref="REF-028, REF-056", niv="Débutant", duree=10, prereq="A-05",
 obj="Encourager l'exploration du canvas et des menus contextuels.",
 tech="Récompense cachée (easter egg)",
 comp="Panel, Param Viewer, Scribble, Cluster",
 enonce="Un composant a été rendu invisible sur ce canvas. Trouve-le, révèle-le et recopie dans le Panel le mot de passe qu'il contient.",
 depart="Un canvas contenant un composant masqué via le menu contextuel.",
 att="Le mot de passe correctement recopié.",
 mode="SingleValue", tol="0", nb=1,
 impl="L'exercice est livré avec un composant dont l'aperçu et l'affichage sont désactivés. Magpie valide sur une chaîne de caractères exacte, insensible à la casse.",
 etapes=["Utiliser Ctrl+A pour sélectionner tout le contenu du canvas et repérer l'élément invisible.",
         "Ou utiliser Metahopper pour lister tous les composants du document.",
         "Réactiver son affichage via le menu contextuel.",
         "Lire le mot de passe et le recopier dans le Panel de réponse."],
 pieges=["Chercher uniquement à l'écran sans utiliser la sélection globale.",
         "Recopier le mot de passe avec un espace parasite."],
 var=["Plusieurs easter eggs dans un même parcours.", "Mot de passe déblocant un exercice bonus."],
 bareme="1 point, plus badge secret EXPLORATEUR."),

dict(id="G-10", titre="Le coffre à butin", them="G2 · Exploration et découverte",
 ref="REF-068, REF-045", niv="Intermédiaire", duree=14, prereq="A-14, A-39",
 obj="Introduire une part d'aléatoire maîtrisé pour renouveler l'intérêt.",
 tech="Récompense aléatoire (loot box)",
 comp="Random, Jitter, Cull Pattern, Rectangular Array, Sphere",
 enonce="Vingt coffres sont disposés en trame. Trois contiennent une récompense, désignés par le tirage aléatoire de graine 7. Identifie-les et affiche leurs index.",
 depart="Une trame de 20 positions et un Random de graine imposée.",
 att="Les trois index corrects affichés dans un Panel.",
 mode="SetEquality", tol="0", nb=8,
 impl="La graine du Random est figée dans le fichier d'exercice : le résultat est donc déterministe et vérifiable, tout en donnant à l'apprenant l'impression d'un tirage.",
 etapes=["Poser Random avec Seed = 7 et Number = 3 dans le domaine 0 à 19.",
         "Arrondir les valeurs avec Round pour obtenir des index entiers.",
         "Poser List Item ou Cull Index pour marquer les coffres correspondants.",
         "Afficher les index dans un Panel."],
 pieges=["Changer la graine : le résultat ne correspond plus à l'attendu.",
         "Random produit des décimales : sans arrondi les index sont invalides."],
 var=["Récompense de rareté variable.", "Coffre à ouvrir en résolvant une énigme."],
 bareme="3 points, 1 par coffre correctement identifié."),

dict(id="G-11", titre="Les mots croisés des composants", them="G2 · Exploration et découverte",
 ref="REF-057, REF-058", niv="Débutant", duree=15, prereq="A-27, A-28",
 obj="Consolider le vocabulaire des composants natifs par un jeu de lettres.",
 tech="Mots croisés et grille de lettres",
 comp="Text Split, Concatenate, List Item, Panel, Text Tag 3D",
 enonce="Complète la grille de mots croisés dessinée sur le canvas. Chaque définition renvoie au nom anglais d'un composant natif. Assemble ensuite les lettres des cases grisées pour former le mot final.",
 depart="Une grille dessinée en Text Tag 3D et une liste de définitions en Scribble.",
 att="Le mot final correctement reconstitué.",
 mode="SingleValue", tol="0", nb=10,
 impl="La grille est produite par un cluster fourni. Magpie valide uniquement le mot final, ce qui rend la correction robuste tout en obligeant à résoudre l'ensemble de la grille.",
 etapes=["Résoudre chaque définition : par exemple « éclate une liste en branches » donne GRAFT.",
         "Saisir chaque réponse dans le Panel correspondant.",
         "Extraire les lettres des cases grisées avec List Item aux index indiqués.",
         "Assembler avec Concatenate et soumettre le mot final."],
 pieges=["Répondre en français alors que les noms de composants sont en anglais.",
         "Index de cases grisées comptés à partir de 1."],
 var=["Grille thématique par domaine du référentiel.", "Version mots mêlés."],
 bareme="1 point par définition, 3 points pour le mot final."),

dict(id="G-12", titre="Le memory des composants", them="G2 · Exploration et découverte",
 ref="REF-047, REF-051, REF-049", niv="Débutant", duree=12, prereq="A-20",
 obj="Associer chaque composant à son effet sur les données, par appariement.",
 tech="Memory et appariement de paires",
 comp="Weave, Cull Pattern, Param Viewer, Panel, Text Tag 3D",
 enonce="Douze cartes affichent d'un côté un nom de composant, de l'autre une structure de données avant/après. Reconstitue les six paires en indiquant les couples d'index.",
 depart="Douze cartes numérotées et douze structures de données affichées.",
 att="Six paires correctement appariées.",
 mode="SetEquality", tol="0", nb=8,
 impl="La réponse attendue est une liste de six couples d'entiers. Magpie valide en mode SetEquality sur les couples normalisés (index le plus petit en premier), l'ordre des paires étant indifférent.",
 etapes=["Analyser chaque structure avec le Param Viewer fourni.",
         "Identifier l'opération réalisée entre l'état avant et l'état après.",
         "Associer cette opération au nom de composant correspondant.",
         "Saisir les six couples dans le Panel de réponse, index le plus petit en premier."],
 pieges=["Confondre Graft et Simplify sur la carte 5.",
         "Saisir les couples dans un ordre interne inversé."],
 var=["Memory chronométré.", "Memory à trois cartes par famille (nom, icône, effet)."],
 bareme="6 points, 1 par paire."),

dict(id="G-13", titre="La machine à sous des motifs", them="G2 · Exploration et découverte",
 ref="REF-045, REF-068", niv="Intermédiaire", duree=15, prereq="A-14, B-03",
 obj="Comprendre la logique des motifs cycliques par une mécanique de rouleaux.",
 tech="Machine à sous et alignement de motifs",
 comp="Cull Pattern, Shift List, Series, Rectangular Array, Colour Swatch",
 enonce="Trois rouleaux affichent chacun une séquence de 8 motifs. Trouve les trois valeurs de décalage qui alignent trois motifs identiques sur la ligne centrale.",
 depart="Trois listes de 8 motifs et trois sliders de décalage.",
 att="Trois motifs identiques alignés et les trois décalages soumis.",
 mode="ExactOrderedList", tol="0", nb=12,
 impl="Magpie valide sur le triplet de décalages. Un seul triplet est correct dans le domaine 0 à 7, ce qui rend la solution unique et vérifiable.",
 etapes=["Lire les trois séquences dans les Panels fournis.",
         "Repérer un motif présent dans les trois séquences.",
         "Calculer pour chaque rouleau le décalage amenant ce motif en position centrale.",
         "Régler les trois sliders et soumettre le triplet."],
 pieges=["Shift List sans Wrap : les positions extrêmes deviennent inaccessibles.",
         "Motif présent dans deux séquences seulement."],
 var=["Rouleaux animés par un Timer.", "Motifs géométriques plutôt que textuels."],
 bareme="3 points, validation sur le triplet exact."),

dict(id="G-14", titre="Le puzzle de câblage", them="G3 · Manipulation et adresse",
 ref="REF-027, REF-048", niv="Débutant", duree=12, prereq="A-01, A-19",
 obj="Travailler la lecture des entrées et sorties d'un composant.",
 tech="Puzzle de connexion à ports contraints",
 comp="Construct Point, Construct Plane, Circle, Rotate, Deconstruct",
 enonce="Six composants sont posés sur le canvas, tous les câbles ont été supprimés. Rétablis le câblage pour reproduire la géométrie affichée en filigrane, sans ajouter ni supprimer aucun composant.",
 depart="Six composants dispersés, aucun câble, une géométrie cible en filigrane.",
 att="La géométrie cible reproduite avec exactement six composants.",
 mode="GeometryTolerance", tol="0,1 mm", nb=6,
 impl="Magpie contrôle simultanément la géométrie produite et le nombre de composants, ce dernier devant rester strictement égal à six. Toute aide par ajout de composant est ainsi éliminée.",
 etapes=["Identifier le composant terminal produisant la géométrie visible.",
         "Remonter la chaîne : quelle entrée attend un plan, laquelle attend un nombre.",
         "Câbler de l'amont vers l'aval en contrôlant le type attendu à chaque port.",
         "Vérifier la superposition avec le filigrane."],
 pieges=["Brancher un point sur une entrée attendant un plan : conversion silencieuse en plan XY à cette origine.",
         "Ajouter un composant pour contourner une difficulté : le contrôle du nombre échoue."],
 var=["Puzzle à 12 composants.", "Version où deux câblages différents donnent le même résultat."],
 bareme="1 point pour la géométrie, 1 point pour le respect du nombre de composants."),

dict(id="G-15", titre="Le dessin à compléter", them="G3 · Manipulation et adresse",
 ref="REF-063, REF-067", niv="Débutant", duree=14, prereq="A-34, A-38",
 obj="Reconstituer une figure par déduction géométrique.",
 tech="Silhouette à compléter et symétrie",
 comp="Mirror, Rotate, Polygon, Arc, Join Curves",
 enonce="La moitié gauche du motif est dessinée. Complète la moitié droite pour obtenir une figure parfaitement symétrique, puis referme le contour.",
 depart="Une demi-figure internalisée et un axe de symétrie.",
 att="Le contour fermé complet et symétrique.",
 mode="GeometryTolerance", tol="0,05 mm", nb=6,
 impl="Magpie valide en GeometryTolerance sur le contour fermé résultant. La fermeture est vérifiée séparément par un booléen renvoyé au plugin.",
 etapes=["Poser Mirror avec le plan de symétrie fourni.",
         "Vérifier que la copie miroir se raccorde exactement à l'original.",
         "Poser Join Curves pour souder les deux moitiés.",
         "Contrôler la fermeture avec un composant de test de courbe fermée."],
 pieges=["Plan de symétrie décalé : un décrochement apparaît à la jonction.",
         "Join Curves sans tolérance suffisante : le contour reste ouvert."],
 var=["Symétrie centrale plutôt qu'axiale.", "Figure à compléter par rotation d'ordre 5."],
 bareme="1 point pour la symétrie, 1 point pour la fermeture."),

dict(id="G-16", titre="La chasse au trésor", them="G3 · Manipulation et adresse",
 ref="REF-055, REF-101", niv="Intermédiaire", duree=18, prereq="A-09, A-45",
 obj="Rechercher une donnée anormale dans un ensemble volumineux.",
 tech="Chasse au trésor et indices successifs",
 comp="Null Item, Bounds, Sort List, Distance, Dispatch, Panel",
 enonce="Parmi 500 points, un seul est aberrant : il est hors du volume de référence. Trouve son index. Trois indices sont disponibles, chacun coûte 2 points.",
 depart="500 points internalisés et un volume de référence.",
 att="L'index du point aberrant.",
 mode="SingleValue", tol="0", nb=8,
 impl="Les trois indices sont fournis dans des groupes repliés du canvas, dont l'ouverture est comptabilisée comme une tentative supplémentaire par Magpie, ce qui réduit le score final.",
 etapes=["Poser un test d'inclusion des points dans le volume de référence.",
         "Récupérer la liste de booléens résultante.",
         "Poser Gate Not puis un composant d'index des True pour localiser le point hors volume.",
         "Afficher son index dans le Panel de réponse."],
 pieges=["Chercher visuellement dans la vue Rhino sur 500 points.",
         "Confondre l'index dans la liste filtrée et l'index dans la liste d'origine."],
 var=["Plusieurs points aberrants.", "Indice révélant une zone au lieu du point."],
 bareme="10 points, moins 2 points par indice consulté."),

dict(id="G-17", titre="Le quiz éclair", them="G4 · Connaissance et mémorisation",
 ref="REF-040, REF-053, REF-056", niv="Débutant", duree=8, prereq="A-06, A-24, A-26",
 obj="Vérifier des connaissances conceptuelles non mesurables par comparaison de géométrie.",
 tech="QCM chronométré à réponse unique",
 comp="Value List, Panel, Boolean Toggle",
 enonce="Dix questions à choix multiple sur les comportements implicites de Grasshopper. Trente secondes par question, une seule réponse possible.",
 depart="Dix Value List pré-configurées.",
 att="Les dix bonnes réponses sélectionnées.",
 mode="ExactOrderedList", tol="0", nb=10,
 impl="Chaque question est une Value List dont la valeur sélectionnée est comparée à la valeur attendue. Ce format couvre les notions conceptuelles du référentiel signalées en mode Conceptuel (QCM).",
 etapes=["Lire chaque question dans le Scribble associé.",
         "Sélectionner la réponse dans la Value List correspondante.",
         "Ne pas modifier l'ordre des questions.",
         "Soumettre l'ensemble en une seule validation."],
 pieges=["Value List laissée sur sa valeur par défaut, comptée comme réponse.",
         "Passer trop de temps sur une question et perdre le bonus de temps."],
 var=["Banque de questions tirées aléatoirement.", "Questions illustrées par une capture de canvas."],
 bareme="10 points, 1 par bonne réponse."),

dict(id="G-18", titre="Vrai ou faux à élimination", them="G4 · Connaissance et mémorisation",
 ref="REF-040, REF-041, REF-059", niv="Débutant", duree=10, prereq="A-06, A-07, A-29",
 obj="Lever les idées reçues sur les conversions et les comparaisons.",
 tech="Vrai/faux à élimination progressive",
 comp="Boolean Toggle, Panel, Gate And",
 enonce="Quinze affirmations sur les types et les conversions. Réponds par vrai ou faux. Une erreur élimine l'affirmation et ses deux suivantes du décompte : mieux vaut réfléchir que deviner.",
 depart="Quinze Boolean Toggle et quinze affirmations en Scribble.",
 att="Les quinze réponses correctes.",
 mode="ExactOrderedList", tol="0", nb=15,
 impl="Magpie compare la liste des quinze booléens à la liste attendue. La règle d'élimination est appliquée au calcul du score, pas à la validation, qui reste à 15/15.",
 etapes=["Traiter chaque affirmation en la vérifiant mentalement sur un cas concret.",
         "En cas de doute, tester rapidement dans un coin du canvas.",
         "Positionner les toggles.",
         "Soumettre l'ensemble."],
 pieges=["Répondre au hasard sur les affirmations portant sur l'arrondi.",
         "Confondre valeur nulle et valeur zéro à l'affirmation 8."],
 var=["Affirmations tirées d'erreurs réellement commises par les apprenants.", "Mode duel à deux."],
 bareme="15 points, avec pénalité d'élimination sur le score."),

dict(id="G-19", titre="Le composant mystère", them="G4 · Connaissance et mémorisation",
 ref="REF-028, REF-042", niv="Intermédiaire", duree=12, prereq="A-05, A-11",
 obj="Identifier un composant par son comportement plutôt que par son nom.",
 tech="Devinette par observation du comportement (boîte noire)",
 comp="Cluster, Panel, Param Viewer, Value List",
 enonce="Quatre clusters anonymes transforment les données. Observe leurs entrées et sorties, puis identifie le composant natif que chacun reproduit.",
 depart="Quatre clusters verrouillés et des jeux de données de test.",
 att="Les quatre noms de composants correctement identifiés.",
 mode="ExactOrderedList", tol="0", nb=8,
 impl="Chaque cluster est protégé par mot de passe pour empêcher son ouverture. La réponse est saisie via quatre Value List proposant chacune huit candidats.",
 etapes=["Alimenter chaque cluster avec une liste simple de 1 à 5 et observer la sortie.",
         "Répéter avec une liste contenant des doublons puis avec un arbre à deux branches.",
         "Déduire la transformation opérée à partir des trois essais.",
         "Sélectionner le nom dans la Value List correspondante."],
 pieges=["Conclure après un seul jeu de test : plusieurs composants ont le même effet sur une liste simple.",
         "Ne pas tester le comportement sur un arbre, seul discriminant entre Flatten et Simplify."],
 var=["Clusters combinant deux composants.", "Épreuve chronométrée."],
 bareme="4 points, 1 par cluster identifié."),

dict(id="G-20", titre="La chasse aux bugs", them="G4 · Connaissance et mémorisation",
 ref="REF-041, REF-053, REF-055", niv="Intermédiaire", duree=20, prereq="A-07, A-09, A-24",
 obj="Développer le réflexe de diagnostic sur une définition qui ne produit pas le résultat attendu.",
 tech="Débogage d'une définition volontairement fautive",
 comp="Param Viewer, Panel, List Length, Null Item, Profiler",
 enonce="Cette définition devrait produire 24 modules, elle n'en produit que 6. Trois défauts se cachent dans le graphe. Identifie-les et corrige la définition sans en changer la structure générale.",
 depart="Une définition fautive de 30 composants.",
 att="24 modules produits et les trois défauts corrigés.",
 mode="SetEquality", tol="0,1 mm", nb=30,
 impl="Magpie valide sur le résultat géométrique et contrôle que le nombre de composants reste inchangé, ce qui interdit de reconstruire la définition plutôt que de la corriger.",
 etapes=["Brancher un Param Viewer en plusieurs points de la chaîne pour localiser la rupture.",
         "Défaut 1 : une correspondance en Shortest List tronque une liste de 24 à 6.",
         "Défaut 2 : un Flatten mal placé écrase la structure d'arbre attendue.",
         "Défaut 3 : une valeur nulle en entrée invalide quatre éléments.",
         "Corriger les trois points et vérifier le compte final."],
 pieges=["Corriger le symptôme en aval plutôt que la cause en amont.",
         "Supprimer le composant fautif au lieu de le régler : le contrôle du nombre échoue."],
 var=["Cinq défauts dont deux sans effet visible.", "Définition fournie par un autre apprenant."],
 bareme="3 points, 1 par défaut corrigé."),

dict(id="G-21", titre="Le golf de composants", them="G5 · Performance et compétition",
 ref="REF-068, REF-043, REF-046", niv="Intermédiaire", duree=20, prereq="A-16, A-39",
 obj="Chercher la solution la plus économe, exercice d'élégance algorithmique.",
 tech="Contrainte de score minimal (code golf)",
 comp="Series, Shift List, Line, Rectangular Array, Graft",
 enonce="Produis la géométrie cible avec le moins de composants possible. Le par du trou est fixé à 7 composants. Sliders et Panels comptent.",
 depart="Une géométrie cible en filigrane.",
 att="La géométrie reproduite, idéalement en 7 composants ou moins.",
 mode="GeometryTolerance", tol="0,1 mm", nb=7,
 impl="Magpie utilise directement la métrique du nombre de composants et l'écart au chemin attendu. Le score de golf est renvoyé comme métrique principale, la validation géométrique restant obligatoire.",
 etapes=["Analyser la cible pour identifier la répétition sous-jacente.",
         "Préférer un composant de réseau à une suite de transformations.",
         "Utiliser les expressions dans les entrées pour éviter des composants de calcul.",
         "Compter les composants et chercher à descendre sous le par."],
 pieges=["Optimiser au détriment de la lisibilité au point de rendre la solution invérifiable.",
         "Oublier que les sliders comptent dans le total."],
 var=["Parcours de 9 trous de difficulté croissante.", "Classement de la promotion sur chaque trou."],
 bareme="Par 7 : 3 points au par, 5 points sous le par, 1 point au-dessus."),

dict(id="G-22", titre="Le boss de fin de chapitre", them="G5 · Performance et compétition",
 ref="REF-047, REF-051, REF-068, REF-079", niv="Perfectionnement", duree=45, prereq="Tous les exercices du chapitre Données"),

dict(id="G-23", titre="Le duel", them="G5 · Performance et compétition",
 ref="REF-082, REF-044", niv="Intermédiaire", duree=20, prereq="B-12",
 obj="Confronter deux approches d'un même problème et en mesurer les écarts.",
 tech="Duel et classement entre apprenants (leaderboard)",
 comp="Sort List, Mass Addition, Length, Panel, Profiler",
 enonce="Même énoncé pour tous : produire la nomenclature triée de l'assemblage. Trois critères départagent les participants : justesse, nombre de composants, temps d'exécution de la définition.",
 depart="Un assemblage identique pour tous les participants.",
 att="La nomenclature exacte, avec les trois métriques relevées.",
 mode="ExactOrderedList", tol="0,5 %", nb=18,
 impl="Magpie remonte les trois métriques déjà collectées par le plugin. Le classement est établi hors de l'outil, à partir des fichiers de résultats exportés en fin de parcours.",
 etapes=["Produire la nomenclature comme dans l'exercice B-12.",
         "Relever le nombre de composants dans le panneau de métriques.",
         "Activer le Profiler pour relever le temps de calcul de la définition.",
         "Soumettre et exporter le résultat."],
 pieges=["Optimiser le temps de calcul au détriment de la justesse.",
         "Comparer des temps mesurés sur des machines différentes."],
 var=["Duel en direct pendant une session de formation.", "Classement par thématique du référentiel."],
 bareme="Classement combiné sur les trois critères, validation à la justesse seule."),

dict(id="G-24", titre="Le retour sonore", them="G6 · Sensations et immersion",
 ref="REF-027, REF-061", niv="Débutant", duree=10, prereq="A-31",
 obj="Associer un retour immédiat perceptible à chaque action correcte ou fautive.",
 tech="Sons et signaux audio contextuels",
 comp="Boolean Toggle, Stream Filter, Panel, Play Sound (Human)",
 enonce="Câble la définition de sorte qu'un son de validation retentisse quand la condition est vraie et un son d'erreur quand elle est fausse. Puis résous l'énigme logique qui déclenche le son de victoire.",
 depart="Deux fichiers audio référencés et un cluster de logique incomplet.",
 att="Les sons correctement déclenchés et l'énigme résolue.",
 mode="SingleValue", tol="0", nb=8,
 impl="Le retour audio s'appuie sur un composant de lecture sonore du plugin Human, ou à défaut sur un composant de son ajouté au plugin Magpie. La validation Magpie porte sur la résolution de l'énigme, le son restant un retour d'expérience.",
 etapes=["Brancher le booléen de condition sur un Stream Filter à deux entrées sonores.",
         "Vérifier l'alternance en basculant manuellement le toggle.",
         "Résoudre l'énigme logique du cluster : trouver la combinaison de trois booléens rendant la sortie vraie.",
         "Soumettre la combinaison."],
 pieges=["Son déclenché à chaque recalcul et non au seul changement d'état.",
         "Chemin de fichier audio absolu, non transportable d'un poste à l'autre."],
 var=["Palette sonore par thématique.", "Son de compte à rebours dans les dix dernières secondes."],
 bareme="2 points : 1 pour le câblage sonore, 1 pour l'énigme."),

dict(id="G-25", titre="L'animation de la solution", them="G6 · Sensations et immersion",
 ref="REF-090, REF-093, REF-067", niv="Perfectionnement", duree=25, prereq="A-37, B-05",
 obj="Rendre visible le déroulement d'un algorithme plutôt que son seul résultat.",
 comp="Timer, Series, Sub List, Move, Custom Preview, Gradient",
 tech="Animation temporelle et révélation progressive",
 enonce="Anime la construction de la structure : les 40 barres doivent apparaître une par une en trois secondes, puis la structure entière change de couleur. Le pilotage se fait par un unique slider de 0 à 1.",
 depart="Une structure de 40 barres déjà modélisée.",
 att="L'animation pilotée par un slider unique, complète à 1.",
 mode="SetEquality", tol="0,1 mm", nb=14,
 impl="L'exercice est validé sur l'état final (slider à 1, 40 barres visibles) et sur un état intermédiaire imposé (slider à 0,5, 20 barres visibles), ce qui garantit que l'animation est bien progressive.",
 etapes=["Multiplier la valeur du slider par 40 et arrondir pour obtenir le nombre de barres visibles.",
         "Construire le domaine 0 à ce nombre avec Construct Domain.",
         "Poser Sub List pour ne conserver que les barres de ce domaine.",
         "Poser Custom Preview avec un Gradient piloté par le même slider.",
         "Vérifier les deux états de contrôle, à 0,5 puis à 1."],
 pieges=["Sub List sur un domaine non entier : le nombre de barres devient imprévisible.",
         "Timer branché en permanence : la définition recalcule sans arrêt et devient inutilisable."],
 var=["Animation par vagues plutôt que séquentielle.", "Export de l'animation en séquence d'images."],
 bareme="2 points : 1 pour l'état final, 1 pour l'état intermédiaire."),

dict(id="G-26", titre="Le retour visuel immédiat", them="G6 · Sensations et immersion",
 ref="REF-026, REF-059", niv="Débutant", duree=12, prereq="A-29",
 obj="Colorer le résultat en fonction de sa conformité, pour un diagnostic instantané.",
 tech="Retour visuel par couleur conditionnelle",
 comp="Custom Preview, Colour Swatch, Stream Filter, Larger Than, Gradient",
 enonce="Vingt pièces doivent mesurer entre 400 et 900 mm. Colore en vert celles qui sont conformes, en rouge les autres, et affiche le nombre de non-conformes.",
 depart="Vingt pièces internalisées de longueurs variées.",
 att="Coloration correcte et compte des non-conformes.",
 mode="SingleValue", tol="0", nb=12,
 impl="La validation Magpie porte sur le nombre de non-conformes. La coloration est un retour d'expérience évalué visuellement par le formateur lors de la revue de l'exercice.",
 etapes=["Mesurer les longueurs avec Length.",
         "Construire le test de conformité avec deux comparaisons et un Gate And.",
         "Séparer les pièces avec Dispatch selon ce booléen.",
         "Poser deux Custom Preview avec deux Colour Swatch distincts.",
         "Compter les non-conformes avec Mass Addition sur le booléen inversé."],
 pieges=["Custom Preview appliqué à la liste complète : toutes les pièces prennent la même couleur.",
         "Aperçu du composant amont resté actif : les deux couleurs se superposent."],
 var=["Dégradé continu plutôt que deux couleurs.", "Coloration par famille de matériau."],
 bareme="2 points : 1 pour la coloration, 1 pour le compte."),

dict(id="G-27", titre="La savane paramétrique", them="G6 · Sensations et immersion",
 ref="REF-063, REF-067, REF-068", niv="Débutant", duree=20, prereq="A-34, A-39",
 obj="Inscrire une série d'exercices dans un fil narratif cohérent avec l'identité de la marque.",
 tech="Narration et univers thématique (scénarisation)",
 comp="Polygon, Circle, Rectangular Array, Move, Custom Preview, Text Tag 3D",
 enonce="Chapitre 1 de la savane : construis l'abreuvoir circulaire, puis dispose la harde de 12 animaux en trame autour du point d'eau, chacun orienté vers le centre.",
 depart="Un décor de fond et un module d'animal simplifié.",
 att="L'abreuvoir et les 12 modules orientés vers le centre.",
 mode="GeometryTolerance", tol="1 mm", nb=14,
 impl="La narration est portée par les Scribbles et le décor du canvas. Magpie valide la géométrie produite ; le fil narratif se déploie sur l'ensemble du parcours via les consignes successives.",
 etapes=["Construire l'abreuvoir par un Circle centré à l'origine.",
         "Répartir 12 positions par Polar Array ou Divide Curve sur un cercle plus grand.",
         "Construire pour chaque position le vecteur pointant vers le centre avec Vector 2Pt.",
         "Orienter chaque module avec Orient ou Rotate selon l'angle calculé.",
         "Vérifier que tous les modules regardent bien le centre."],
 pieges=["Vecteur construit du centre vers la position : les animaux tournent le dos à l'eau.",
         "Angle calculé sans Atan2 : l'orientation est fausse sur deux quadrants."],
 var=["Chapitres successifs formant un parcours complet.", "Personnages débloqués par les badges."],
 bareme="2 points : 1 pour la disposition, 1 pour l'orientation."),

dict(id="G-28", titre="L'avatar paramétrique", them="G6 · Sensations et immersion",
 ref="REF-067, REF-106, REF-061", niv="Intermédiaire", duree=22, prereq="B-16, A-31",
 obj="Faire construire à l'apprenant un objet personnel qu'il retrouvera tout au long du parcours.",
 tech="Avatar et personnalisation persistante",
 comp="Value List, Stream Filter, Polygon, Circle, Colour Swatch, Custom Preview",
 enonce="Compose ton avatar : 3 formes de corps, 4 motifs, 6 couleurs. Ton avatar doit rester valide dans les 72 combinaisons possibles et son code de configuration doit s'afficher dans le Panel.",
 depart="Trois Value List et les bibliothèques de formes et de motifs.",
 att="L'avatar composé et son code de configuration affiché.",
 mode="SingleValue", tol="0", nb=20,
 impl="Le code de configuration (par exemple B2-M3-C5) est la donnée validée par Magpie. Il est conservé dans le profil de l'apprenant et repris sur le certificat.",
 etapes=["Sélectionner la forme active avec Stream Filter piloté par la première Value List.",
         "Appliquer le motif choisi par la même mécanique.",
         "Appliquer la couleur avec un Colour Swatch sélectionné par la troisième Value List.",
         "Composer le code avec Concatenate à partir des trois index.",
         "Balayer les 72 combinaisons pour vérifier qu'aucune ne produit d'erreur."],
 pieges=["Value List renvoyant du texte plutôt qu'un entier : Stream Filter échoue.",
         "Combinaisons non testées : certaines produisent une géométrie invalide."],
 var=["Avatar évoluant avec le niveau atteint.", "Avatar exporté en image pour le certificat."],
 bareme="2 points : 1 pour la robustesse, 1 pour le code de configuration."),

dict(id="G-29", titre="Le défi du jour", them="G7 · Régularité et communauté",
 ref="REF-047, REF-079", niv="Intermédiaire", duree=10, prereq="A-13, A-47",
 obj="Installer une habitude de pratique par une tâche courte et renouvelée.",
 tech="Défi quotidien à énoncé variable",
 comp="Random, Series, Sort List, Length, Panel",
 enonce="Un défi court, différent chaque jour, tiré d'une banque de 30 micro-tâches. Celui du jour : trie les pièces par longueur et donne la longueur médiane.",
 depart="Une banque de micro-tâches et un jeu de données du jour.",
 att="La réponse au défi du jour.",
 mode="NumericTolerance", tol="0,1 %", nb=10,
 impl="Le fichier JSON de l'exercice contient les 30 variantes. Le plugin sélectionne la variante à partir de la date du poste, ce qui rend le défi identique pour tous les apprenants d'une même journée.",
 etapes=["Lire l'énoncé du jour affiché dans le Scribble.",
         "Mesurer les longueurs avec Length.",
         "Trier avec Sort List.",
         "Extraire l'élément médian avec List Length, une division par 2 et List Item.",
         "Soumettre la valeur."],
 pieges=["Confondre médiane et moyenne.",
         "Liste de taille paire : la médiane est la moyenne des deux valeurs centrales."],
 var=["Série de sept jours donnant un badge hebdomadaire.", "Défi collectif avec objectif commun."],
 bareme="1 point par défi, badge à 7 jours consécutifs."),

dict(id="G-30", titre="Le relais à deux", them="G7 · Régularité et communauté",
 ref="REF-088, REF-048", niv="Perfectionnement", duree=30, prereq="B-05, A-21",
 obj="Travailler la lisibilité et la transmissibilité d'une définition.",
 tech="Mode coopératif en relais",
 comp="Cluster, Group, Param Viewer, Scribble, Metahopper",
 enonce="Première moitié : construis la structure de données jusqu'au point de passage marqué, en la rendant compréhensible par un tiers. Ton binôme reprendra le fichier pour la seconde moitié sans explication orale.",
 depart="Un énoncé en deux parties et un point de passage matérialisé sur le canvas.",
 att="La définition complète produite par les deux contributions successives.",
 mode="SetEquality", tol="0,1 mm", nb=30,
 impl="L'exercice est livré en deux fichiers JSON enchaînés. Le fichier intermédiaire produit par le premier apprenant sert de point de départ au second, ce qui suppose la fonction d'import de composants de départ déjà présente dans Magpie.",
 etapes=["Construire la première moitié en nommant explicitement toutes les sorties.",
         "Regrouper les blocs fonctionnels avec Group et les titrer.",
         "Documenter les hypothèses dans des Scribbles.",
         "Transmettre le fichier au binôme.",
         "Le binôme complète sans poser de question et signale les points restés obscurs."],
 pieges=["Nommage par défaut conservé : le binôme perd du temps à décoder.",
         "Structure d'arbre non documentée au point de passage."],
 var=["Relais à quatre sur un projet complet.", "Évaluation croisée de la lisibilité."],
 bareme="4 points : 2 pour le résultat, 2 pour la lisibilité évaluée par le binôme."),

dict(id="G-31", titre="L'arbre de compétences", them="G7 · Régularité et communauté",
 ref="REF-048, REF-051", niv="Intermédiaire", duree=15, prereq="A-19, A-22"),

dict(id="G-32", titre="Les indices payants", them="G7 · Régularité et communauté",
 ref="REF-052, REF-049, REF-050", niv="Intermédiaire", duree=20, prereq="A-20, A-21, A-23",
 obj="Responsabiliser l'apprenant sur le recours à l'aide.",
 tech="Économie d'indices à coût décroissant sur le score",
 comp="Path Mapper, Graft, Flatten, Simplify, Param Viewer",
 enonce="Restructure l'arbre fourni pour atteindre la structure cible. Quatre indices sont disponibles, du plus général au plus précis, coûtant respectivement 1, 2, 3 et 4 points sur un total de 12.",
 depart="Un arbre source, une structure cible affichée et quatre groupes d'indices repliés.",
 att="La structure cible atteinte.",
 mode="SetEquality", tol="0", nb=6,
 impl="Chaque indice est un groupe du canvas dont l'ouverture est détectée par Magpie comme un événement, décomptée du score final. Le mécanisme réutilise le compteur de tentatives du plugin.",
 etapes=["Comparer les chemins source et cible dans le Param Viewer.",
         "Identifier l'opération nécessaire : ajout de niveau, suppression, permutation.",
         "Appliquer Path Mapper avec les masques adaptés.",
         "Vérifier la structure obtenue avant de soumettre."],
 pieges=["Utiliser Flatten puis Graft pour reconstruire : la structure obtenue diffère de la cible.",
         "Consommer les quatre indices avant d'avoir essayé."],
 var=["Indices sous forme de vidéo courte.", "Indices offerts par une série de bonnes réponses."],
 bareme="12 points, moins le coût des indices consultés."),
]

# --- Exercices dont la fiche est completee ci-dessous (redaction en deux temps)
_COMPLEMENTS = {
"G-22": dict(
 obj="Éprouver en une seule tâche l'ensemble des notions du chapitre Données et logique.",
 tech="Affrontement final de chapitre (boss fight) à phases successives",
 comp="Series, Sort List, Cull Pattern, Graft, Path Mapper, Gate And, Dispatch, Mass Addition",
 enonce="Trois phases s'enchaînent sans validation intermédiaire. Phase 1 : structurer les données en arbre. Phase 2 : filtrer selon deux conditions combinées. Phase 3 : produire le tableau de synthèse. Toute erreur en phase 3 impose de reprendre depuis la phase 1.",
 depart="Un jeu de 240 valeurs et un modèle de tableau de sortie.",
 att="Le tableau de synthèse exact.",
 mode="ExactOrderedList", tol="0,1 %", nb=32,
 impl="Le boss est un exercice unique agrégeant trois sous-critères, tous nécessaires à la validation. Le seuil de réussite est fixé à 100 %, contrairement aux exercices ordinaires du chapitre.",
 etapes=["Phase 1 : répartir les 240 valeurs en 12 branches de 20 avec Partition List puis contrôler au Param Viewer.",
         "Phase 2 : construire les deux conditions et les combiner avec Gate And.",
         "Phase 2 : filtrer chaque branche avec Dispatch en conservant la structure d'arbre.",
         "Phase 3 : calculer par branche le compte, la somme et la moyenne avec Mass Addition et Average.",
         "Phase 3 : assembler le tableau avec Merge dans l'ordre imposé et soumettre."],
 pieges=["Aplatir l'arbre en phase 2 : les statistiques de phase 3 portent alors sur l'ensemble et non par branche.",
         "Ordre des colonnes du tableau non respecté.",
         "Moyenne calculée sur la liste filtrée mais compte calculé sur la liste complète."],
 var=["Boss de chapitre pour chaque domaine du référentiel.", "Version chronométrée avec classement."],
 bareme="10 points, validation à 100 % uniquement."),

"G-31": dict(
 obj="Donner à l'apprenant une vue d'ensemble de son avancement et des chemins possibles.",
 tech="Carte de progression et arbre de compétences (skill tree)",
 comp="Tree Statistics, Param Viewer, Text Tag 3D, Line, Circle, Custom Preview",
 enonce="Construis la représentation graphique de ton propre arbre de compétences à partir de la liste des exercices validés : un nœud par notion, une branche par domaine, un code couleur par niveau atteint.",
 depart="La liste des exercices validés exportée par Magpie et la structure du référentiel.",
 att="L'arbre de compétences dessiné, cohérent avec les données d'entrée.",
 mode="SetEquality", tol="1 mm", nb=22,
 impl="Le fichier de résultats exporté en fin de parcours alimente l'exercice. La lecture de ce fichier suppose une fonction d'import de résultats à ajouter au plugin, actuellement absente du prototype.",
 etapes=["Lire le fichier de résultats et en extraire les identifiants d'exercices validés.",
         "Rattacher chaque identifiant à son domaine et à sa catégorie via la table du référentiel.",
         "Construire l'arbre de données correspondant avec Entwine puis Path Mapper.",
         "Placer un nœud par notion sur un cercle par domaine.",
         "Relier les nœuds à leur domaine avec Line et colorer selon le niveau atteint.",
         "Étiqueter chaque nœud avec Text Tag 3D."],
 pieges=["Structure d'arbre construite à plat : les domaines se mélangent.",
         "Nœuds superposés faute d'avoir réparti les angles selon le nombre de notions par domaine."],
 var=["Arbre mis à jour automatiquement après chaque parcours.", "Comparaison avec la moyenne de la promotion."],
 bareme="4 points : 2 pour la structure, 2 pour la lisibilité."),
}

for _e in LOT_G:
    if _e["id"] in _COMPLEMENTS:
        _e.update(_COMPLEMENTS[_e["id"]])
