# -*- coding: utf-8 -*-
"""LOT B - Algorithmes combines (niveau Intermediaire) et LOT C - Projets appliques (Experimente)."""

LOT_B = [

dict(id="B-01", titre="Escalier droit paramétrique", them="B1 · Architecture et construction",
 ref="REF-067, REF-068, REF-047, REF-043", niv="Intermédiaire", duree=25, prereq="A-37, A-39, A-10",
 obj="Chaîner série, transformation et extrusion pour produire un ouvrage réglementé par un calcul.",
 comp="Series, Division, Round, Move, Extrude, Rectangle, Mass Addition",
 enonce="Produis un escalier droit reliant deux niveaux distants de H = 2 850 mm. Le giron est fixé à 280 mm et la hauteur de marche doit rester comprise entre 165 et 180 mm. Détermine automatiquement le nombre de marches et vérifie la règle de Blondel (2h + g compris entre 600 et 650 mm).",
 depart="Deux Number Slider (H = 2850, giron = 280) et un Panel de contrôle.",
 att="L'escalier modélisé, le nombre de marches et la valeur de Blondel affichés.",
 mode="NumericTolerance", tol="1 mm sur la hauteur de marche", nb=18,
 etapes=["Diviser H par 172,5 (hauteur moyenne visée) puis arrondir avec Round : on obtient le nombre de contremarches.",
         "Recalculer la hauteur réelle h = H / nombre de contremarches.",
         "Générer avec Series les positions verticales (0 à H, pas h) et horizontales (0 à n×giron, pas giron).",
         "Construire le vecteur de déplacement de chaque marche avec Construct Point puis Vector 2Pt.",
         "Poser le rectangle de marche (giron × largeur) et le déplacer par la liste de vecteurs.",
         "Extruder chaque marche de l'épaisseur choisie.",
         "Calculer 2h + g et le contrôler avec deux Larger Than et un Gate And : afficher CONFORME ou NON CONFORME."],
 pieges=["Confondre nombre de marches et nombre de contremarches : il y a toujours une contremarche de plus.",
         "Arrondir la hauteur de marche au lieu de recalculer h à partir du nombre entier de contremarches.",
         "Oublier que la dernière marche est confondue avec le plancher haut."],
 var=["Ajouter un limon latéral suivant la ligne de foulée.",
      "Passer en escalier à volée tournante avec un Polar Array partiel.",
      "Sortir une nomenclature des marches vers CSV."],
 gamif="G-02 Barre de progression + G-26 Feedback visuel", bareme="2 points pour la géométrie, 1 point pour le nombre de marches, 1 point pour le contrôle de Blondel."),

dict(id="B-02", titre="Garde-corps à barreaudage régulier", them="B1 · Architecture et construction",
 ref="REF-064, REF-047, REF-043", niv="Intermédiaire", duree=20, prereq="A-35, A-12",
 obj="Répartir des éléments à pas maximal imposé, cas classique de calcul d'entraxe.",
 comp="Divide Curve, Length, Division, Round, Pipe, Line",
 enonce="Sur la main courante fournie, place des barreaux verticaux de 16 mm de diamètre. L'espacement libre entre barreaux ne doit jamais dépasser 110 mm. Détermine le nombre de barreaux et affiche l'entraxe réel.",
 depart="Une courbe de main courante et une hauteur de garde-corps internalisées.",
 att="Les barreaux modélisés et un Panel affichant nombre et entraxe.",
 mode="NumericTolerance", tol="0,5 mm", nb=14,
 etapes=["Mesurer la longueur de la main courante avec Length.",
         "Calculer le pas maximal admissible : 110 + 16 = 126 mm.",
         "Diviser la longueur par 126 puis arrondir à l'entier supérieur (Round avec le mode Ceiling ou Ceiling direct).",
         "Recalculer l'entraxe réel = longueur / nombre d'intervalles.",
         "Poser Divide Curve avec ce nombre d'intervalles.",
         "Tracer les segments verticaux depuis chaque point puis les transformer en Pipe de rayon 8.",
         "Afficher nombre et entraxe dans un Panel."],
 pieges=["Confondre entraxe et espacement libre : l'écart libre vaut entraxe moins le diamètre.",
         "Arrondir à l'entier le plus proche au lieu de l'entier supérieur : l'espacement dépasse la limite.",
         "Oublier les barreaux d'extrémité."],
 var=["Suivre une main courante inclinée en gardant les barreaux verticaux.",
      "Ajouter une lisse basse et calculer le linéaire total de matière."],
 gamif="G-07 Étoiles de performance", bareme="2 points pour le barreaudage, 1 point pour le respect strict des 110 mm."),

dict(id="B-03", titre="Façade à trame variable pilotée par un attracteur", them="B1 · Architecture et construction",
 ref="REF-068, REF-053, REF-054", niv="Intermédiaire", duree=30, prereq="A-39, A-25",
 obj="Faire varier un paramètre géométrique en fonction d'une distance, méthode fondamentale du paramétrique.",
 comp="Rectangular Array, Distance, Remap Numbers, Bounds, Circle, Region Difference",
 enonce="Sur la trame de façade 12 × 8, perce chaque panneau d'une ouverture circulaire dont le rayon varie de 50 mm (loin de l'attracteur) à 350 mm (au plus près). Le point attracteur est déplaçable dans Rhino.",
 depart="Une surface de façade et un point attracteur référencés.",
 att="96 panneaux percés d'ouvertures de rayon variable.",
 mode="GeometryTolerance", tol="1 mm", nb=16,
 etapes=["Diviser la façade avec Divide Surface ou Rectangular Array pour obtenir les 96 centres de panneaux.",
         "Mesurer la distance de chaque centre à l'attracteur avec Distance.",
         "Poser Bounds sur ces distances pour obtenir le domaine réel.",
         "Poser Remap Numbers : source = domaine des distances, cible = domaine 350 à 50 (inversé).",
         "Poser Circle avec les centres et les rayons remappés.",
         "Percer les panneaux avec Region Difference (2D) ou Solid Difference (3D).",
         "Vérifier que le rayon reste inférieur à la demi-largeur du panneau."],
 pieges=["Domaine cible non inversé : les grandes ouvertures se retrouvent au plus loin.",
         "Rayon supérieur à la demi-largeur : la découpe déborde sur les panneaux voisins.",
         "Attracteur non internalisé : la définition casse à l'ouverture du fichier."],
 var=["Piloter la rotation des panneaux plutôt que le rayon.",
      "Utiliser une courbe attractrice au lieu d'un point.",
      "Contraindre le taux de vide global à une valeur cible."],
 gamif="G-25 Animation + G-13 Casino motifs assortis", bareme="2 points pour la variation, 1 point pour la borne de sécurité du rayon."),

dict(id="B-04", titre="Pavage hexagonal sur surface", them="B1 · Architecture et construction",
 ref="REF-068, REF-069, REF-049", niv="Intermédiaire", duree=28, prereq="B-03, A-20",
 obj="Projeter une trame plane sur une surface libre en maîtrisant la structure de données.",
 comp="Hexagonal (Lunchbox ou natif Polygon), Surface Closest Point, Evaluate Surface, Graft",
 enonce="Applique un pavage hexagonal de 400 mm de côté sur la surface libre fournie, puis extrude chaque hexagone de 60 mm suivant la normale locale de la surface.",
 depart="Une surface libre internalisée.",
 att="Le pavage projeté et extrudé selon les normales.",
 mode="GeometryTolerance", tol="2 mm", nb=20,
 etapes=["Construire la trame hexagonale plane par deux Rectangular Array décalés d'un demi-pas.",
         "Poser Polygon avec 6 côtés sur chaque centre.",
         "Projeter les centres sur la surface avec Surface Closest Point.",
         "Récupérer les normales avec Evaluate Surface (sortie N).",
         "Construire un plan local par centre avec Plane Normal.",
         "Orienter les hexagones sur ces plans avec Orient.",
         "Extruder chaque hexagone suivant sa normale : Graft nécessaire pour associer un vecteur par hexagone."],
 pieges=["Oublier le Graft : tous les hexagones reçoivent le même vecteur.",
         "Trame plane plus petite que la surface : des zones restent non pavées.",
         "Surface très courbe : les hexagones se chevauchent."],
 var=["Faire varier la hauteur d'extrusion selon la courbure locale.",
      "Découper les hexagones dépassant du contour de la surface."],
 gamif="G-22 Boss de fin de chapitre", bareme="2 points pour le pavage, 2 points pour l'orientation selon les normales."),

dict(id="B-05", titre="Poutre treillis paramétrique", them="B1 · Architecture et construction",
 ref="REF-046, REF-063, REF-079", niv="Intermédiaire", duree=25, prereq="A-16, A-47",
 obj="Construire une structure par décalage de listes et produire directement son métré.",
 comp="Series, Shift List, Line, Pipe, Length, Mass Addition, Weave",
 enonce="Produis une poutre treillis Warren de 12 000 mm de portée et 900 mm de hauteur, avec 8 panneaux. Affiche le linéaire total de tube nécessaire, membrures et diagonales séparées.",
 depart="Trois sliders : portée, hauteur, nombre de panneaux.",
 att="Le treillis modélisé et deux valeurs de linéaire.",
 mode="NumericTolerance", tol="0,5 %", nb=22,
 etapes=["Générer les abscisses des nœuds avec Range sur la portée.",
         "Construire la membrure basse (Z = 0) et la membrure haute (Z = 900) par Construct Point.",
         "Relier chaque nœud au suivant avec Shift List + Line pour les deux membrures.",
         "Pour les diagonales, alterner nœud bas i vers nœud haut i+1 puis nœud haut i+1 vers nœud bas i+2 : utiliser Cull Pattern ou Weave.",
         "Transformer les lignes en Pipe avec deux diamètres distincts.",
         "Mesurer les longueurs avec Length puis Mass Addition sur chaque famille.",
         "Afficher les deux linéaires dans un Panel."],
 pieges=["Shift List sans Wrap : la dernière barre manque ou la première est en trop.",
         "Alternance des diagonales mal construite : on obtient un treillis Pratt et non Warren.",
         "Compter deux fois les nœuds partagés dans le métré."],
 var=["Passer d'un treillis Warren à un treillis Pratt par un simple changement de motif.",
      "Exporter la nomenclature des barres vers Excel.",
      "Faire varier la hauteur pour obtenir une poutre à inertie variable."],
 gamif="G-21 Golf de composants", bareme="2 points pour la géométrie, 2 points pour les deux linéaires."),

dict(id="B-06", titre="Caisson de meuble avec épaisseur et rainures", them="B2 · Design de mobilier",
 ref="REF-070, REF-071, REF-068", niv="Intermédiaire", duree=30, prereq="A-43, A-44",
 obj="Modéliser un assemblage menuisé où toutes les cotes dérivent de trois paramètres.",
 comp="Box, Solid Difference, Move, Deconstruct Box, Construct Domain",
 enonce="Modélise un caisson de largeur L, hauteur H et profondeur P, en panneaux de 19 mm. Les joues reçoivent une rainure de 6 mm de profondeur pour le fond de 8 mm. Le dessus et le dessous s'insèrent entre les joues.",
 depart="Trois sliders L, H, P et un slider d'épaisseur.",
 att="Le caisson en 5 panneaux distincts, rainures comprises.",
 mode="GeometryTolerance", tol="0,1 mm", nb=26,
 etapes=["Construire le volume englobant à partir de L, H, P.",
         "Déduire la géométrie de chaque joue : épaisseur × H × P, positionnée à gauche et à droite.",
         "Déduire dessus et dessous : (L − 2 × 19) × 19 × P, positionnés entre les joues.",
         "Construire le volume de rainure : boîte de 8 mm d'épaisseur, profondeur 6 mm, courant sur toute la hauteur.",
         "Soustraire cette boîte des quatre panneaux avec Solid Difference.",
         "Poser le fond de 8 mm dans la rainure, avec un jeu de 0,2 mm.",
         "Contrôler visuellement l'assemblage en vue éclatée par un Move paramétrable."],
 pieges=["Oublier de retirer deux épaisseurs à la longueur du dessus et du dessous.",
         "Rainure positionnée au nu arrière sans tenir compte de sa profondeur.",
         "Jeu de montage nul : les pièces s'interpénètrent lors du contrôle de collision."],
 var=["Passer d'un assemblage rainuré à un assemblage par tourillons.",
      "Ajouter une nomenclature de débit avec chants.",
      "Générer la vue éclatée animée."],
 gamif="G-06 Niveaux et déblocage", bareme="3 points pour l'assemblage, 1 point pour la rainure correcte."),

dict(id="B-07", titre="Tiroir paramétrique avec jeux fonctionnels", them="B2 · Design de mobilier",
 ref="REF-070, REF-072", niv="Intermédiaire", duree=25, prereq="B-06, A-46",
 obj="Intégrer des jeux de fonctionnement et vérifier l'absence de collision.",
 comp="Box, Solid Difference, Collision Many|Many, Boolean Toggle, Move",
 enonce="Insère dans le caisson un tiroir sur coulisses de 13 mm de jeu latéral par côté et 2 mm en hauteur. Le tiroir doit pouvoir coulisser de toute sa profondeur sans collision : prouve-le.",
 depart="Le caisson de l'exercice B-06.",
 att="Le tiroir modélisé et un Panel affichant l'absence de collision en position ouverte.",
 mode="SingleValue", tol="—", nb=20,
 etapes=["Calculer la largeur intérieure disponible : L − 2 × 19.",
         "Déduire la largeur du tiroir : intérieur − 2 × 13.",
         "Construire le caisson de tiroir en panneaux de 15 mm.",
         "Poser un slider de course de 0 à P pour piloter l'ouverture.",
         "Déplacer le tiroir de cette course avec Move.",
         "Poser Collision Many|Many entre les panneaux du tiroir et ceux du caisson.",
         "Afficher dans un Panel le nombre de collisions détectées : il doit rester à zéro sur toute la course."],
 pieges=["Appliquer le jeu une seule fois au lieu de deux fois (un par côté).",
         "Tester la collision uniquement en position fermée.",
         "Tolérance de collision de Grasshopper trop lâche : un contact tangent passe inaperçu."],
 var=["Ajouter une façade en applique avec débord.",
      "Générer plusieurs tiroirs de hauteurs différentes réparties automatiquement."],
 gamif="G-04 Système de vies", bareme="2 points pour le tiroir, 2 points pour la preuve d'absence de collision."),

dict(id="B-08", titre="Étagère modulaire à pas variable", them="B2 · Design de mobilier",
 ref="REF-043, REF-044, REF-047", niv="Intermédiaire", duree=22, prereq="A-13, A-10",
 obj="Répartir des tablettes selon une progression non uniforme pilotée par une courbe.",
 comp="Graph Mapper, Range, Remap Numbers, Move, Box, Sort List",
 enonce="Répartis 6 tablettes sur une hauteur de 2 000 mm de sorte que les entre-deux augmentent progressivement du bas vers le haut, la plus petite hauteur libre valant au moins 220 mm.",
 depart="Un slider de hauteur totale et un slider de nombre de tablettes.",
 att="Les tablettes réparties et un Panel listant les hauteurs libres.",
 mode="ExactOrderedList", tol="1 mm", nb=16,
 etapes=["Générer une série normalisée de 0 à 1 avec Range.",
         "Passer cette série dans un Graph Mapper réglé en courbe puissance.",
         "Remapper le résultat sur le domaine 0 à 2000 : les positions se resserrent en bas.",
         "Poser les tablettes à ces altitudes avec Move.",
         "Calculer les entre-deux par Shift List et soustraction, puis retirer l'épaisseur de tablette.",
         "Contrôler la valeur minimale avec Bounds et un Larger Than.",
         "Afficher les hauteurs libres dans un Panel."],
 pieges=["Oublier de retirer l'épaisseur des tablettes pour obtenir la hauteur libre.",
         "Graph Mapper non internalisé : la courbe se réinitialise à l'ouverture du fichier.",
         "Contrainte de 220 mm vérifiée sur les entraxes et non sur les vides."],
 var=["Inverser la progression du haut vers le bas.",
      "Imposer un nombre entier de modules standards."],
 gamif="G-08 Combo / série", bareme="2 points pour la répartition, 1 point pour la contrainte de 220 mm."),

dict(id="B-09", titre="Griffe de sertissage paramétrique", them="B3 · Joaillerie",
 ref="REF-068, REF-069, REF-067", niv="Intermédiaire", duree=28, prereq="A-39, A-42",
 obj="Construire un détail technique répétitif autour d'un axe, avec contrôle d'inclinaison.",
 comp="Polar Array, Pipe, Rotate Axis, Circle, Sweep 1, Interpolate",
 enonce="Modélise 4 griffes réparties à 90° autour d'une pierre ronde de 5 mm de diamètre. Chaque griffe est un fil de 0,9 mm de diamètre, incliné de 12° vers l'intérieur, avec une tête arrondie recouvrant la ceinture de la pierre.",
 depart="Un slider de diamètre de pierre et une sphère de gabarit.",
 att="4 griffes correctement réparties et inclinées.",
 mode="GeometryTolerance", tol="0,02 mm", nb=22,
 etapes=["Construire le cercle de ceinture de la pierre.",
         "Tracer le profil d'une griffe par Interpolate sur 3 ou 4 points de contrôle.",
         "Incliner ce profil de 12° avec Rotate Axis autour d'un axe tangent au cercle.",
         "Transformer le profil en solide avec Pipe de rayon 0,45.",
         "Répartir par Polar Array avec Count = 4 et Angle = 2π.",
         "Vérifier que la tête de griffe recouvre bien la ceinture par une intersection Brep|Brep.",
         "Contrôler l'absence de collision entre griffes voisines."],
 pieges=["Angle saisi en degrés au lieu de radians.",
         "Axe de rotation mal choisi : les griffes s'inclinent hors du plan attendu.",
         "Pipe de rayon égal au diamètre : la griffe fait le double de la cote demandée."],
 var=["Passer à 6 griffes et vérifier la non-collision.",
      "Faire varier l'inclinaison en fonction du diamètre de pierre.",
      "Ajouter un panier sous la pierre."],
 gamif="G-10 Coffre à butin", bareme="2 points pour la géométrie, 1 point pour l'inclinaison, 1 point pour le recouvrement."),

dict(id="B-10", titre="Motif gravé développé sur un anneau", them="B3 · Joaillerie",
 ref="REF-115, REF-069, REF-049", niv="Intermédiaire", duree=30, prereq="B-04, A-42",
 obj="Concevoir un motif à plat puis l'enrouler sur une surface de révolution.",
 comp="Rectangle, Divide Domain2, Surface Morph, Flow along Surface (Morph), Revolution",
 enonce="Dessine à plat un motif géométrique répétitif de 12 modules, puis applique-le sur la face extérieure d'un anneau de taille 54 et de 4 mm de large. Le motif doit boucler sans rupture.",
 depart="Un anneau de révolution internalisé et un module de motif plan.",
 att="Le motif appliqué sur l'anneau, raccord continu.",
 mode="GeometryTolerance", tol="0,05 mm", nb=24,
 etapes=["Calculer la circonférence de l'anneau : diamètre intérieur = 54/π, puis circonférence extérieure.",
         "Diviser cette circonférence par 12 pour obtenir la largeur exacte du module.",
         "Construire le motif dans un rectangle de référence exactement de cette largeur.",
         "Répliquer le module 12 fois avec Rectangular Array.",
         "Construire la surface développée de référence (rectangle circonférence × largeur).",
         "Appliquer Surface Morph ou Sporph entre la surface plane et la surface de l'anneau.",
         "Vérifier la continuité au raccord en superposant le premier et le dernier module."],
 pieges=["Largeur de module arrondie : le raccord présente un décalage cumulé.",
         "Confondre diamètre intérieur et diamètre extérieur pour le calcul de circonférence.",
         "Surface de référence et surface cible de proportions différentes : le motif se déforme."],
 var=["Rendre le nombre de modules paramétrable et recalculer automatiquement la largeur.",
      "Graver le motif en creux par Solid Difference.",
      "Adapter au cas d'un anneau de section variable."],
 gamif="G-09 Récompense cachée", bareme="2 points pour le motif, 2 points pour la continuité du raccord."),

dict(id="B-11", titre="Chaîne de maillons le long d'une courbe", them="B3 · Joaillerie",
 ref="REF-064, REF-067, REF-046", niv="Intermédiaire", duree=25, prereq="A-35, A-38",
 obj="Répartir et orienter alternativement des éléments le long d'un parcours.",
 comp="Divide Length, Perp Frames, Orient, Cull Pattern, Rotate, Torus",
 enonce="Répartis des maillons ovales de 4 mm le long de la courbe fournie, chaque maillon tourné de 90° par rapport au précédent, sans jeu ni recouvrement excessif.",
 depart="Une courbe de collier internalisée.",
 att="La chaîne complète avec alternance des orientations.",
 mode="GeometryTolerance", tol="0,05 mm", nb=20,
 etapes=["Poser Divide Length avec un pas égal au pas de maillon (longueur moins recouvrement).",
         "Poser Perp Frames pour obtenir un plan par position.",
         "Modéliser un maillon de référence dans le plan XY.",
         "Orienter le maillon sur chaque plan avec Orient.",
         "Séparer les positions paires et impaires avec Cull Pattern (motif True, False).",
         "Appliquer une rotation de 90° (π/2) aux maillons impairs avec Rotate Axis.",
         "Recombiner les deux familles avec Weave pour retrouver l'ordre initial."],
 pieges=["Pas de division égal à la longueur du maillon : les maillons ne se touchent pas.",
         "Recombiner avec Merge au lieu de Weave : l'ordre est perdu.",
         "Courbe trop courbée : les maillons se coincent."],
 var=["Faire varier la taille des maillons selon la position sur la courbe.",
      "Ajouter un fermoir aux extrémités."],
 gamif="G-12 Memory", bareme="2 points pour la répartition, 2 points pour l'alternance."),

dict(id="B-12", titre="Nomenclature automatique et export CSV", them="B4 · Données, métrés et livrables",
 ref="REF-082, REF-083, REF-085, REF-087", niv="Intermédiaire", duree=25, prereq="A-27, A-47",
 obj="Transformer un modèle en tableau de données exploitable.",
 comp="Deconstruct Brep, Volume, Area, Sort List, Concatenate, Format, Text Join, Write File",
 enonce="À partir du modèle fourni, produis une nomenclature triée par volume décroissant comportant, pour chaque pièce, le repère, le volume en dm³, la surface en dm² et la masse en kg pour une densité de 700 kg/m³. Exporte le tableau au format CSV.",
 depart="Un assemblage de 14 solides internalisés.",
 att="Un fichier CSV de 14 lignes plus l'en-tête, trié par volume décroissant.",
 mode="ExactOrderedList", tol="0,5 %", nb=24,
 etapes=["Mesurer Volume et Area de chaque solide.",
         "Convertir les unités : mm³ vers dm³ (division par 1 000 000), mm² vers dm² (division par 10 000).",
         "Calculer la masse : volume en m³ multiplié par 700.",
         "Générer les repères avec Series et Format (masque PCE-{0:000}).",
         "Trier l'ensemble par volume décroissant avec Sort List puis Reverse List, en propageant toutes les listes.",
         "Formater chaque valeur à deux décimales avec Format.",
         "Assembler chaque ligne avec Concatenate et le séparateur point-virgule.",
         "Ajouter la ligne d'en-tête avec Merge, puis écrire le fichier avec Write File."],
 pieges=["Trier une seule liste et pas les autres : les données se désynchronisent.",
         "Séparateur décimal virgule et séparateur de colonne virgule : le CSV devient illisible.",
         "Oublier l'en-tête ou le placer après le tri."],
 var=["Ajouter une colonne matériau lue depuis les calques Rhino.",
      "Grouper les pièces identiques et compter les occurrences.",
      "Exporter vers Excel plutôt que CSV."],
 gamif="G-01 Score visible", bareme="2 points pour les calculs, 1 point pour le tri, 1 point pour le format du fichier."),

dict(id="B-13", titre="Calepinage de plaques et calcul de chute", them="B4 · Données, métrés et livrables",
 ref="REF-113, REF-082, REF-045", niv="Intermédiaire", duree=28, prereq="B-12, A-15",
 obj="Optimiser un débit et quantifier la perte matière.",
 comp="Rectangular Array, Region Difference, Area, Mass Addition, Division, Dispatch",
 enonce="Les 22 pièces rectangulaires fournies doivent être débitées dans des plaques de 2 800 × 2 070 mm. Calcule le nombre de plaques nécessaires et le taux de chute en pourcentage.",
 depart="Une liste de 22 rectangles et les dimensions de plaque.",
 att="Un Panel affichant le nombre de plaques et le taux de chute.",
 mode="NumericTolerance", tol="1 %", nb=20,
 etapes=["Mesurer l'aire de chaque pièce avec Area puis sommer avec Mass Addition.",
         "Calculer l'aire d'une plaque : 2800 × 2070.",
         "Diviser l'aire totale des pièces par l'aire d'une plaque et arrondir à l'entier supérieur : nombre théorique minimal.",
         "Placer les pièces par un calepinage simple en bandes (tri par hauteur décroissante puis remplissage ligne par ligne).",
         "Compter le nombre réel de plaques utilisées.",
         "Calculer le taux de chute : 1 − (aire des pièces / aire des plaques utilisées).",
         "Afficher les deux valeurs et signaler l'écart avec le minimum théorique."],
 pieges=["Confondre le minimum théorique et le nombre réellement atteignable.",
         "Oublier le trait de scie entre les pièces.",
         "Ne pas gérer les pièces plus grandes que la plaque."],
 var=["Ajouter une contrainte de sens de fil du bois.",
      "Comparer le résultat avec l'imbrication OpenNest.",
      "Chiffrer le coût matière à partir du prix de plaque."],
 gamif="G-23 Duel et classement", bareme="2 points pour le calepinage, 1 point pour le nombre de plaques, 1 point pour le taux de chute."),

dict(id="B-14", titre="Numérotation et étiquetage automatiques", them="B4 · Données, métrés et livrables",
 ref="REF-066, REF-081, REF-057", niv="Intermédiaire", duree=22, prereq="A-49, A-27",
 obj="Produire des repères lisibles, cohérents et positionnés dans le modèle.",
 comp="Sort List, Series, Format, Text Tag 3D, Volume, Point, Plane",
 enonce="Numérote les 14 pièces de l'assemblage de gauche à droite puis de bas en haut, au format R-A01 à R-A14, et place l'étiquette au centre de gravité de chaque pièce, orientée face à la vue de face.",
 depart="Un assemblage de 14 solides internalisés.",
 att="14 étiquettes correctement numérotées et positionnées.",
 mode="ExactOrderedList", tol="1 mm", nb=18,
 etapes=["Récupérer les centroïdes avec Volume.",
         "Décomposer les points avec Deconstruct pour obtenir X et Z.",
         "Construire une clé de tri combinée : Z multiplié par un grand facteur plus X.",
         "Trier les pièces et les centroïdes avec Sort List sur cette clé.",
         "Générer les numéros avec Series et Format (masque R-A{0:00}).",
         "Poser Text Tag 3D avec un plan orienté XZ pour la lisibilité en vue de face.",
         "Contrôler l'ordre obtenu dans un Panel."],
 pieges=["Clé de tri mal pondérée : le tri secondaire prend le pas sur le tri principal.",
         "Format sans masque : les numéros s'affichent sans zéro de tête.",
         "Étiquettes orientées dans le plan XY donc illisibles en élévation."],
 var=["Ajouter le repère dans un attribut Rhino via Elefront.",
      "Générer une planche de repérage cotée."],
 gamif="G-11 Mots croisés de composants", bareme="2 points pour l'ordre, 1 point pour le format, 1 point pour le placement."),

dict(id="B-15", titre="Optimisation d'une découpe linéaire", them="B4 · Données, métrés et livrables",
 ref="REF-044, REF-045, REF-082", niv="Intermédiaire", duree=30, prereq="B-13",
 obj="Mettre en œuvre un algorithme de placement glouton et en mesurer la performance.",
 comp="Sort List, Reverse List, Anemone ou Python, Mass Addition, Panel",
 enonce="Débite 30 pièces de longueurs variées dans des barres de 6 000 mm. Applique la règle du plus grand d'abord et affiche le nombre de barres consommées ainsi que la chute totale.",
 depart="Une liste de 30 longueurs internalisée.",
 att="Un Panel affichant le nombre de barres et la chute totale en mm.",
 mode="SingleValue", tol="0", nb=18,
 etapes=["Trier les longueurs par ordre décroissant avec Sort List puis Reverse List.",
         "Mettre en place une boucle Anemone : à chaque itération, tenter de placer la pièce suivante dans une barre ouverte.",
         "Si aucune barre ne peut l'accueillir, ouvrir une nouvelle barre.",
         "Accumuler l'état des barres dans la boucle avec un paramètre de rebouclage.",
         "En sortie de boucle, compter les barres et sommer les chutes.",
         "Afficher les deux valeurs.",
         "Comparer avec le minimum théorique (somme des longueurs divisée par 6000, arrondi supérieur)."],
 pieges=["Boucle sans condition d'arrêt : Grasshopper se fige.",
         "Oublier le trait de scie dans le cumul.",
         "Tri croissant au lieu de décroissant : le résultat se dégrade nettement."],
 var=["Comparer avec une stratégie du meilleur ajustement.",
      "Écrire l'algorithme en composant Python plutôt qu'en boucle Anemone.",
      "Autoriser plusieurs longueurs de barre commerciale."],
 gamif="G-23 Duel et classement + G-03 Compte à rebours", bareme="2 points pour l'algorithme, 1 point pour le nombre de barres, 1 point pour la chute."),

dict(id="B-16", titre="Lampe à lamelles de section variable", them="B5 · Design produit",
 ref="REF-064, REF-069, REF-067", niv="Intermédiaire", duree=28, prereq="A-35, A-41",
 obj="Faire varier une section le long d'un parcours par interpolation contrôlée.",
 comp="Divide Curve, Perp Frames, Circle, Graph Mapper, Loft, Polar Array",
 enonce="Produis un abat-jour composé de 24 lamelles réparties autour d'un axe. Chaque lamelle suit un profil dont la largeur varie de 15 mm aux extrémités à 45 mm au milieu, selon une courbe douce.",
 depart="Une courbe génératrice internalisée et un slider de nombre de lamelles.",
 att="24 lamelles réparties, largeur variable respectée.",
 mode="GeometryTolerance", tol="0,2 mm", nb=22,
 etapes=["Diviser la courbe génératrice en 30 stations avec Divide Curve.",
         "Générer une série normalisée de 0 à 1 sur ces stations.",
         "Passer cette série dans un Graph Mapper en courbe de Bézier symétrique.",
         "Remapper la sortie sur le domaine 15 à 45 : on obtient la largeur à chaque station.",
         "Construire un rectangle de cette largeur dans le plan perpendiculaire de chaque station.",
         "Lofter ces rectangles pour obtenir la lamelle.",
         "Répartir par Polar Array avec Count = 24."],
 pieges=["Graph Mapper non symétrique : les deux extrémités n'ont pas la même largeur.",
         "Rectangles non alignés : le Loft se vrille.",
         "Lamelles voisines en interférence près de l'axe."],
 var=["Faire varier aussi l'épaisseur.",
      "Contrôler l'ouverture lumineuse résultante.",
      "Adapter le nombre de lamelles à un diamètre imposé."],
 gamif="G-28 Avatar et personnalisation", bareme="2 points pour la variation, 2 points pour la répartition."),

dict(id="B-17", titre="Coque à nervures depuis une surface libre", them="B5 · Design produit",
 ref="REF-069, REF-101, REF-049", niv="Intermédiaire", duree=30, prereq="A-45, B-04",
 obj="Extraire des sections structurelles d'une forme libre et préparer leur fabrication.",
 comp="Brep | Plane, Offset Curve, Extrude, Series, Rectangle, Boundary Surfaces",
 enonce="Sur la coque libre fournie, extrais 9 nervures transversales espacées régulièrement, donne-leur 12 mm d'épaisseur et 60 mm de hauteur vers l'intérieur, puis prépare leur mise à plat.",
 depart="Une surface de coque internalisée.",
 att="9 nervures modélisées et leur développé à plat.",
 mode="GeometryTolerance", tol="0,5 mm", nb=24,
 etapes=["Poser Bounding Box puis Deconstruct Box pour connaître l'étendue en X.",
         "Générer 9 plans de coupe régulièrement espacés avec Range et YZ Plane.",
         "Poser Brep | Plane pour obtenir les 9 courbes de section.",
         "Décaler chaque section vers l'intérieur de 60 mm avec Offset Curve.",
         "Construire la surface de nervure entre la section et son décalé avec Boundary Surfaces ou Loft.",
         "Extruder de 12 mm pour donner l'épaisseur.",
         "Aligner chaque nervure à plat par Orient vers le plan XY pour la mise à plat."],
 pieges=["Offset Curve du mauvais côté : la nervure sort de la coque.",
         "Courbes de section multiples sur une coque non convexe : les traiter en arbre.",
         "Oublier de conserver le repérage des nervures après mise à plat."],
 var=["Ajouter des encoches d'assemblage aux croisements avec des longerons.",
      "Exporter les développés en DXF.",
      "Faire varier l'espacement selon la courbure."],
 gamif="G-22 Boss de fin de chapitre", bareme="2 points pour les nervures, 2 points pour la mise à plat."),

dict(id="B-18", titre="Filetage hélicoïdal paramétrique", them="B5 · Design produit",
 ref="REF-069, REF-103", niv="Intermédiaire", duree=28, prereq="A-42",
 obj="Construire une hélice et balayer un profil normalisé le long de celle-ci.",
 comp="Helix (Curve > Primitive), Sweep 1, Perp Frames, Polygon, Solid Difference, Cylinder",
 enonce="Modélise une vis M10 au pas de 1,5 mm sur 30 mm de longueur filetée, profil triangulaire à 60°, et vérifie que le diamètre à fond de filet correspond bien à la valeur normalisée de 8,376 mm.",
 depart="Trois sliders : diamètre nominal, pas, longueur filetée.",
 att="La vis modélisée et un Panel affichant le diamètre à fond de filet mesuré.",
 mode="NumericTolerance", tol="0,05 mm", nb=22,
 etapes=["Construire l'hélice avec le composant Helix : rayon 5, pas 1,5, nombre de tours = 30 / 1,5 = 20.",
         "Construire le profil triangulaire du filet ISO dans un plan perpendiculaire au départ de l'hélice.",
         "Poser Sweep 1 avec l'hélice comme rail et le profil comme section.",
         "Construire le cylindre nominal de diamètre 10.",
         "Soustraire le balayage du cylindre avec Solid Difference.",
         "Couper le résultat par un plan passant par l'axe et mesurer le diamètre à fond de filet.",
         "Comparer à 8,376 mm avec Similarity et afficher CONFORME ou NON CONFORME."],
 pieges=["Nombre de tours calculé à partir de la longueur totale et non de la longueur filetée.",
         "Profil non perpendiculaire à l'hélice : le filet se vrille.",
         "Confondre le pas et le pas hélicoïdal sur un filetage multiple."],
 var=["Modéliser l'écrou correspondant et vérifier le jeu.",
      "Paramétrer pour toute la série métrique M3 à M20.",
      "Ajouter un chanfrein d'entrée."],
 gamif="G-32 Indices payants", bareme="2 points pour le filetage, 2 points pour la vérification dimensionnelle."),
]


LOT_C = [

dict(id="C-01", titre="Enveloppe à brise-soleil orientés selon l'ensoleillement", them="C1 · Architecture",
 ref="REF-027, REF-068, REF-095, REF-079", niv="Expérimenté", duree=90, prereq="B-03, B-04",
 obj="Construire une enveloppe dont chaque élément réagit à une donnée d'analyse, et justifier le résultat par une mesure.",
 comp="Divide Surface, Evaluate Surface, Vector 2Pt, Angle, Rotate Axis, Remap Numbers, Area, Galapagos",
 enonce="La façade sud du bâtiment reçoit 180 lames brise-soleil. Oriente chaque lame perpendiculairement à la direction du soleil au 21 juin à 15 h, puis optimise l'angle moyen pour limiter la surface exposée à 40 % de la surface vitrée tout en préservant au moins 25 % de vue directe.",
 depart="Une façade, un vecteur solaire et le contour vitré internalisés.",
 att="Les 180 lames orientées, deux indicateurs affichés, un jeu de paramètres optimisé.",
 mode="NumericTolerance", tol="2 %", nb=45,
 etapes=["Diviser la façade en 180 stations avec Divide Surface.",
         "Récupérer les plans locaux avec Evaluate Surface.",
         "Construire le vecteur solaire à partir de l'azimut et de la hauteur fournis.",
         "Calculer pour chaque station l'angle entre la normale de lame et le vecteur solaire avec Angle.",
         "Faire tourner chaque lame avec Rotate Axis autour de son axe horizontal.",
         "Projeter les lames sur le plan perpendiculaire au soleil et mesurer l'aire projetée cumulée avec Area.",
         "Calculer le taux d'ombrage et le taux de vue directe.",
         "Brancher Galapagos sur l'angle de base et l'amplitude de variation, fonction objectif combinant les deux critères.",
         "Lancer l'optimisation et internaliser le meilleur jeu de paramètres."],
 pieges=["Aires projetées additionnées sans traiter les recouvrements entre lames.",
         "Fonction objectif à un seul critère : l'optimiseur ferme totalement la façade.",
         "Galapagos relié à un slider non borné : la recherche n'aboutit pas."],
 var=["Étendre l'étude à quatre dates de référence.",
      "Piloter la largeur de lame plutôt que son angle.",
      "Produire la nomenclature des lames par angle distinct."],
 gamif="G-22 Boss de fin de chapitre + G-23 Classement", bareme="4 points géométrie, 3 points indicateurs, 3 points optimisation."),

dict(id="C-02", titre="Résille structurelle sur plan libre", them="C1 · Architecture",
 ref="REF-069, REF-094, REF-074, REF-049", niv="Expérimenté", duree=90, prereq="B-04, C-01",
 obj="Générer une structure maillée relaxée et en extraire les données de fabrication.",
 comp="Mesh, Kangaroo, Weaverbird, Pipe, Deconstruct Mesh, Sort List, Text Tag 3D",
 enonce="Sur le contour libre fourni, génère une toiture en résille triangulée, relaxe-la par Kangaroo pour obtenir une forme en équilibre de traction, puis produis la nomenclature des barres regroupées par longueur à 5 mm près et la liste des nœuds avec leur nombre de branches.",
 depart="Un contour fermé et trois points d'appui internalisés.",
 att="La résille relaxée, la nomenclature des barres et celle des nœuds.",
 mode="NumericTolerance", tol="1 %", nb=50,
 etapes=["Mailler le contour avec Mesh Surface ou Delaunay Mesh.",
         "Extraire les arêtes du maillage avec Deconstruct Mesh et Mesh Edges.",
         "Configurer Kangaroo : Length goal sur les arêtes, Anchor sur les appuis, Load vertical.",
         "Lancer la relaxation jusqu'à convergence et figer le résultat.",
         "Mesurer la longueur de chaque arête avec Length.",
         "Regrouper les longueurs par tranche de 5 mm avec une division, un Round et un Create Set.",
         "Compter les occurrences de chaque groupe avec Member Index.",
         "Compter le nombre d'arêtes par sommet pour caractériser les nœuds.",
         "Produire les deux tableaux et les exporter."],
 pieges=["Relaxation non figée : le résultat change à chaque recalcul et la nomenclature devient instable.",
         "Regroupement par arrondi au plus proche : deux barres de 102 et 108 mm tombent dans des groupes différents alors qu'elles sont à 6 mm l'une de l'autre.",
         "Arêtes comptées deux fois car partagées par deux faces."],
 var=["Comparer une résille triangulée et une résille quadrangulaire.",
      "Ajouter une contrainte de longueur maximale de barre.",
      "Générer les platines de nœud."],
 gamif="G-25 Animation de la relaxation", bareme="4 points structure, 3 points nomenclature barres, 3 points nomenclature nœuds."),

dict(id="C-03", titre="Gradins avec contrôle de visibilité", them="C1 · Architecture",
 ref="REF-047, REF-079, REF-046, REF-060", niv="Expérimenté", duree=80, prereq="B-01, B-08",
 obj="Construire une géométrie pilotée par une contrainte de performance vérifiée rang par rang.",
 comp="Series, Shift List, Line, Angle, Larger Than, Gate And, Extrude, Graph Mapper",
 enonce="Modélise 18 rangs de gradins de 850 mm de profondeur. La ligne de visée de chaque spectateur vers le point focal doit passer au moins 90 mm au-dessus de la tête du spectateur du rang précédent. Détermine automatiquement la hauteur de chaque marche et signale tout rang non conforme.",
 depart="Le point focal, la profondeur de rang et le nombre de rangs.",
 att="Les 18 rangs conformes et un tableau de contrôle du dégagement obtenu par rang.",
 mode="NumericTolerance", tol="1 mm", nb=35,
 etapes=["Poser le premier rang à une altitude de départ connue.",
         "Pour chaque rang, calculer la hauteur minimale garantissant 90 mm de dégagement par géométrie de la ligne de visée.",
         "Mettre en place le calcul cumulatif avec une boucle Anemone ou un composant Python, la hauteur d'un rang dépendant du précédent.",
         "Générer les positions de tous les rangs.",
         "Construire le profil en gradins par PolyLine puis extruder sur la largeur.",
         "Recalculer a posteriori le dégagement réel de chaque rang.",
         "Contrôler avec Larger Than et afficher le tableau de conformité."],
 pieges=["Calcul non cumulatif : le dégagement se dégrade à partir du troisième rang.",
         "Hauteur d'œil du spectateur oubliée (environ 1 200 mm en position assise).",
         "Vérification effectuée sur la hauteur de marche et non sur le dégagement de visée."],
 var=["Comparer une courbe de gradins optimisée et une pente constante.",
      "Ajouter les circulations et les paliers.",
      "Calculer le volume de béton."],
 gamif="G-02 Barre de progression + G-20 Erreur à débusquer", bareme="4 points géométrie, 3 points calcul cumulatif, 3 points contrôle."),

dict(id="C-04", titre="Métré et chiffrage complet d'un module", them="C1 · Architecture",
 ref="REF-082, REF-083, REF-084, REF-086", niv="Expérimenté", duree=75, prereq="B-12, B-13",
 obj="Produire un livrable économique complet à partir d'un modèle, avec traçabilité des hypothèses.",
 comp="Deconstruct Brep, Area, Volume, Sort List, Create Set, Member Index, Concatenate, Write File",
 enonce="À partir du module constructif fourni, produis un devis quantitatif estimatif par lot (gros œuvre, menuiserie, second œuvre) avec quantités, unités, prix unitaires et totaux, ainsi qu'un récapitulatif par lot et un total général. Le calcul doit rester juste si l'on modifie les dimensions du module.",
 depart="Un module constructif complet et une table de prix unitaires internalisée.",
 att="Un fichier CSV de devis structuré par lot avec sous-totaux et total général.",
 mode="NumericTolerance", tol="0,5 %", nb=45,
 etapes=["Classer les solides par lot à partir de leur calque d'origine via Geometry Pipeline.",
         "Mesurer les quantités pertinentes par lot : volumes pour le gros œuvre, surfaces pour le second œuvre, linéaires pour les menuiseries.",
         "Convertir chaque quantité dans son unité de devis (m³, m², ml).",
         "Associer chaque poste à son prix unitaire par Member Index dans la table des prix.",
         "Calculer les totaux par poste puis les sous-totaux par lot avec Mass Addition sur arbre.",
         "Calculer le total général.",
         "Composer les lignes de texte avec Concatenate et Format à deux décimales.",
         "Écrire le fichier CSV et vérifier la recalculabilité en modifiant une dimension du module."],
 pieges=["Sous-totaux calculés sur l'arbre aplati : les lots se mélangent.",
         "Prix unitaires codés en dur dans le graphe au lieu d'une table.",
         "Doubles comptes entre postes (une paroi comptée en volume et en surface)."],
 var=["Ajouter un coefficient de perte par lot.",
      "Produire une variante haute et une variante basse.",
      "Exporter vers Excel avec mise en forme."],
 gamif="G-01 Score visible + G-29 Défi quotidien", bareme="4 points quantités, 3 points structure du devis, 3 points recalculabilité."),

dict(id="C-05", titre="Bibliothèque paramétrique avec débit et mise à plat CNC", them="C2 · Design de mobilier",
 ref="REF-070, REF-082, REF-115, REF-087", niv="Expérimenté", duree=90, prereq="B-06, B-12, B-17",
 obj="Aller du modèle paramétrique au fichier de fabrication, en passant par la nomenclature.",
 comp="Box, Solid Difference, Orient, Rectangle, Text Tag 3D, Sort List, Write File",
 enonce="Modélise une bibliothèque de largeur, hauteur et profondeur paramétrables, à montants verticaux tous les 800 mm maximum et tablettes réglables. Produis la nomenclature de débit et la mise à plat repérée de tous les panneaux, prête pour la CNC.",
 depart="Trois sliders de dimensions générales et un slider d'épaisseur de panneau.",
 att="Le meuble modélisé, la nomenclature de débit et les panneaux mis à plat et repérés.",
 mode="GeometryTolerance", tol="0,2 mm", nb=50,
 etapes=["Calculer le nombre de travées : largeur divisée par 800, arrondi supérieur.",
         "Répartir les montants et en déduire la largeur réelle de travée.",
         "Construire montants, traverses et tablettes par Box paramétrés.",
         "Percer les rangées de trous de tablettes par un réseau de cylindres et Solid Difference.",
         "Extraire la face principale de chaque panneau avec Deconstruct Brep et un tri par aire.",
         "Orienter chaque face vers le plan XY avec Orient.",
         "Répartir les panneaux à plat sans recouvrement par un calepinage simple.",
         "Repérer chaque panneau avec Text Tag 3D et produire la nomenclature de débit.",
         "Contrôler que le total des surfaces à plat correspond à la somme des faces d'origine."],
 pieges=["Faces sélectionnées par index fixe : le tri casse dès qu'un panneau change de forme.",
         "Panneaux mis à plat qui se recouvrent.",
         "Repères perdus lors de la mise à plat car non propagés en parallèle des géométries."],
 var=["Ajouter des portes et calculer leurs jeux.",
      "Générer le fichier DXF des panneaux.",
      "Ajouter une contrainte de nombre de plaques disponibles."],
 gamif="G-06 Niveaux et déblocage + G-05 Badges", bareme="4 points modèle, 3 points nomenclature, 3 points mise à plat."),

dict(id="C-06", titre="Chaise à assise en lamelles courbes", them="C2 · Design de mobilier",
 ref="REF-069, REF-064, REF-074", niv="Expérimenté", duree=85, prereq="B-16, B-17",
 obj="Conjuguer une forme ergonomique libre et une contrainte de fabrication en lamelles droites.",
 comp="Interpolate, Divide Curve, Perp Frames, Loft, Sweep 1, Curvature, Larger Than",
 enonce="Modélise l'assise et le dossier d'une chaise en 22 lamelles de 40 mm de large et 8 mm d'épaisseur suivant deux courbes directrices. Le rayon de courbure de chaque lamelle ne doit jamais descendre sous 350 mm, limite de cintrage du matériau : signale toute lamelle non conforme.",
 depart="Deux courbes directrices internalisées.",
 att="Les 22 lamelles et un tableau de contrôle du rayon minimal par lamelle.",
 mode="NumericTolerance", tol="1 mm", nb=42,
 etapes=["Diviser les deux directrices en 22 stations.",
         "Construire la courbe de chaque lamelle par Interpolate entre les points correspondants.",
         "Récupérer les plans perpendiculaires au départ de chaque lamelle.",
         "Construire la section de 40 × 8 mm et la balayer le long de chaque lamelle avec Sweep 1.",
         "Échantillonner chaque lamelle avec Divide Curve et mesurer la courbure.",
         "Convertir en rayon de courbure et prendre le minimum par lamelle avec Bounds.",
         "Comparer à 350 mm avec Larger Than et afficher les lamelles non conformes en rouge.",
         "Ajuster les directrices jusqu'à conformité générale."],
 pieges=["Courbure mesurée sur un échantillonnage trop grossier : le point critique est manqué.",
         "Confondre courbure et rayon de courbure (l'un est l'inverse de l'autre).",
         "Sections non perpendiculaires : les lamelles se vrillent."],
 var=["Ajouter le piètement et vérifier la stabilité par le centre de gravité.",
      "Faire varier la largeur de lamelle selon la zone.",
      "Produire les gabarits de cintrage."],
 gamif="G-26 Feedback visuel + G-07 Étoiles", bareme="4 points géométrie, 3 points contrôle de courbure, 3 points conformité générale."),

dict(id="C-07", titre="Table de nuit configurable", them="C2 · Design de mobilier",
 ref="REF-070, REF-072, REF-082, REF-106", niv="Expérimenté", duree=80, prereq="B-06, B-07",
 obj="Produire un configurateur complet, avec variantes discrètes et contrôle de cohérence.",
 comp="Stream Filter, Box, Solid Difference, Collision Many|Many, Value List, Volume, Concatenate",
 enonce="Réalise un configurateur de table de nuit : 4 types de pieds au choix, de 1 à 3 tiroirs, deux matériaux avec des épaisseurs différentes. Le modèle doit rester valide dans toutes les combinaisons et produire son prix estimatif.",
 depart="Une Value List de types de pied, un slider de nombre de tiroirs, une Value List de matériau.",
 att="Le meuble reconfiguré à la volée et un Panel affichant le prix.",
 mode="GeometryTolerance", tol="0,2 mm", nb=48,
 etapes=["Modéliser les quatre familles de pieds dans des groupes distincts.",
         "Sélectionner la famille active avec Stream Filter piloté par la Value List.",
         "Déduire l'épaisseur de panneau du matériau choisi via Member Index dans une table.",
         "Répartir automatiquement les tiroirs sur la hauteur disponible selon leur nombre.",
         "Appliquer les jeux fonctionnels et vérifier l'absence de collision dans chaque configuration.",
         "Mesurer les volumes par matériau et appliquer les prix unitaires.",
         "Composer le libellé de configuration et le prix dans un Panel.",
         "Balayer systématiquement les 24 combinaisons pour vérifier qu'aucune ne produit d'erreur."],
 pieges=["Une seule combinaison testée : les cas limites (3 tiroirs, panneau épais) échouent.",
         "Stream Filter alimenté par une Value List dont les valeurs ne sont pas des entiers consécutifs.",
         "Hauteur de tiroir négative quand la hauteur disponible est insuffisante."],
 var=["Ajouter une poignée au choix.",
      "Publier le configurateur sur le web avec ShapeDiver.",
      "Générer la fiche produit PDF."],
 gamif="G-28 Avatar + G-10 Coffre à butin", bareme="4 points configurateur, 3 points robustesse, 3 points chiffrage."),

dict(id="C-08", titre="Bague solitaire complète", them="C3 · Joaillerie",
 ref="REF-069, REF-068, REF-081, REF-079", niv="Expérimenté", duree=85, prereq="B-09, B-10",
 obj="Assembler plusieurs sous-ensembles techniques en un bijou complet, avec contrôle de poids.",
 comp="Revolution, Polar Array, Sweep 1, Solid Union, Volume, Multiplication, Collision",
 enonce="Modélise une bague solitaire pour une pierre ronde de 6,5 mm : anneau de taille paramétrable, chaton, panier et 4 griffes. Contrôle que la masse en or 750 reste inférieure à 3,2 g et que la hauteur totale ne dépasse pas 8 mm.",
 depart="Un slider de taille de doigt et un slider de diamètre de pierre.",
 att="La bague complète et deux indicateurs : masse et hauteur.",
 mode="NumericTolerance", tol="0,05 g et 0,05 mm", nb=45,
 etapes=["Calculer le diamètre intérieur à partir de la taille française : diamètre = (taille + 40) / π.",
         "Construire le profil de l'anneau et le révolutionner.",
         "Construire le chaton et le panier par balayage et révolution.",
         "Reprendre les griffes de l'exercice B-09 et les répartir par Polar Array.",
         "Unir l'ensemble avec Solid Union et vérifier que le résultat est un solide unique fermé.",
         "Mesurer le volume total et le multiplier par la masse volumique de l'or 750 (environ 15,6 g/cm³).",
         "Mesurer la hauteur totale par Bounding Box.",
         "Afficher les deux indicateurs avec un test de conformité."],
 pieges=["Solid Union renvoyant plusieurs solides : des éléments ne se touchent pas réellement.",
         "Volume en mm³ multiplié directement par une masse volumique en g/cm³.",
         "Taille de doigt confondue avec le diamètre."],
 var=["Ajouter un pavage sur le corps de bague.",
      "Optimiser le profil pour minimiser la masse à rigidité constante.",
      "Produire la vue technique cotée."],
 gamif="G-05 Badges + G-09 Récompense cachée", bareme="4 points géométrie, 3 points unicité du solide, 3 points indicateurs."),

dict(id="C-09", titre="Pavage de pierres sur surface libre", them="C3 · Joaillerie",
 ref="REF-068, REF-101, REF-080, REF-045", niv="Expérimenté", duree=85, prereq="B-04, C-08",
 obj="Répartir des éléments de tailles variées sur une surface courbe en respectant des distances minimales.",
 comp="Populate Geometry, Surface Closest Point, Evaluate Surface, Distance, Cull Pattern, Sphere, Solid Difference",
 enonce="Pave la surface libre fournie de pierres rondes de 1,2 à 2,5 mm réparties de manière quasi aléatoire mais sans jamais laisser moins de 0,3 mm de métal entre deux pierres voisines. Perce ensuite les logements coniques correspondants.",
 depart="Une surface libre internalisée et un slider de densité.",
 att="Les pierres réparties, aucune distance inter-pierres inférieure à 0,3 mm, et les logements percés.",
 mode="NumericTolerance", tol="0,01 mm", nb=48,
 etapes=["Semer des points sur la surface avec Populate Geometry.",
         "Attribuer un diamètre aléatoire à chaque point avec Random dans le domaine 1,2 à 2,5.",
         "Calculer les distances entre paires de points voisins avec Closest Points.",
         "Comparer chaque distance à la somme des deux rayons plus 0,3 mm.",
         "Éliminer itérativement les points en conflit avec un Cull Pattern piloté par ce test, dans une boucle Anemone.",
         "Récupérer les normales locales avec Evaluate Surface et construire un plan par pierre.",
         "Modéliser chaque pierre et son logement conique dans ce plan.",
         "Percer la surface épaissie avec Solid Difference.",
         "Recontrôler a posteriori que la distance minimale est respectée."],
 pieges=["Test de distance effectué sur les centres sans tenir compte des rayons.",
         "Élimination en une seule passe : de nouveaux conflits apparaissent après suppression.",
         "Logements percés perpendiculairement au plan global et non à la normale locale."],
 var=["Imposer une densité variable pilotée par un attracteur.",
      "Trier les pierres par taille et produire la nomenclature de commande.",
      "Calculer le poids en carats."],
 gamif="G-13 Casino motifs assortis + G-16 Chasse au trésor", bareme="4 points répartition, 3 points respect de la distance, 3 points logements."),

dict(id="C-10", titre="Motif gravé génératif sur bijou", them="C3 · Joaillerie",
 ref="REF-115, REF-095, REF-069", niv="Expérimenté", duree=80, prereq="B-10, C-08",
 obj="Produire un motif non répétitif contrôlé par des règles, puis le graver physiquement.",
 comp="Voronoi, Random, Offset Curve, Surface Morph, Solid Difference, Area, Galapagos",
 enonce="Génère sur le corps de bague un motif de type Voronoï dont les cellules mesurent entre 0,8 et 2,2 mm², sépare les cellules par un filet de 0,25 mm, grave à 0,3 mm de profondeur, et fais en sorte que le motif boucle sans rupture visible.",
 depart="La bague de l'exercice C-08 et un slider de densité de motif.",
 att="Le motif gravé, continu au raccord, cellules dans le domaine d'aire imposé.",
 mode="NumericTolerance", tol="0,05 mm²", nb=45,
 etapes=["Construire la surface développée du corps de bague (rectangle circonférence × largeur).",
         "Semer des points avec Populate 2D dans ce rectangle, en dupliquant une bande aux deux extrémités pour assurer la continuité du raccord.",
         "Générer le diagramme de Voronoï sur ces points.",
         "Décaler chaque cellule vers l'intérieur de 0,125 mm avec Offset Curve pour créer le filet.",
         "Mesurer l'aire de chaque cellule et éliminer celles hors du domaine 0,8 à 2,2 mm².",
         "Appliquer le motif sur la surface de la bague par Surface Morph.",
         "Extruder vers l'intérieur de 0,3 mm et soustraire avec Solid Difference.",
         "Vérifier la continuité au raccord et régler la densité par Galapagos si nécessaire."],
 pieges=["Points semés uniquement dans le rectangle : le raccord présente une rupture nette.",
         "Offset produisant des cellules dégénérées pour les petites cellules.",
         "Profondeur de gravure supérieure à l'épaisseur locale de l'anneau."],
 var=["Remplacer le Voronoï par un motif hexagonal déformé.",
      "Faire varier la profondeur de gravure selon la position.",
      "Exporter en STL pour impression cire."],
 gamif="G-27 Narration Serengeti + G-09 Récompense cachée", bareme="4 points motif, 3 points contraintes d'aire, 3 points raccord."),

dict(id="C-11", titre="Déroulé de tôle pliée avec compensation", them="C4 · Fabrication",
 ref="REF-116, REF-115, REF-082", niv="Expérimenté", duree=80, prereq="B-17, C-05",
 obj="Calculer un développé industriel exact et produire le plan de pliage.",
 comp="Brep | Plane, Unroll (Squid ou Python), Length, Series, Text Tag 3D, Write File",
 enonce="La pièce en tôle de 2 mm comporte 5 plis à 90° de rayon intérieur 3 mm. Produis son développé en tenant compte du facteur K de 0,44, cote les lignes de pli et vérifie que la longueur développée calculée correspond à la longueur mesurée sur le développé.",
 depart="Une pièce en tôle pliée internalisée et les paramètres matière.",
 att="Le développé à plat, les lignes de pli cotées et la vérification de longueur.",
 mode="NumericTolerance", tol="0,1 mm", nb=40,
 etapes=["Identifier les faces planes et les zones de pli par analyse des normales.",
         "Calculer pour chaque pli la longueur de la fibre neutre : (rayon intérieur + K × épaisseur) × angle en radians.",
         "Sommer les longueurs des faces planes et des fibres neutres pour obtenir la longueur développée théorique.",
         "Déplier la pièce face par face avec Orient successifs, ou utiliser un composant de dépliage.",
         "Insérer les longueurs de fibre neutre entre les faces dépliées.",
         "Tracer les lignes de pli et les coter avec Text Tag 3D en indiquant le sens de pliage.",
         "Mesurer la longueur du développé obtenu et la comparer à la valeur théorique.",
         "Exporter le développé en DXF."],
 pieges=["Utiliser le rayon extérieur au lieu du rayon intérieur dans la formule.",
         "Angle de pli confondu avec l'angle d'ouverture (90° de pli correspond à un angle complémentaire selon la convention).",
         "Facteur K appliqué à l'épaisseur totale au lieu de la position de la fibre neutre."],
 var=["Traiter des plis à angles quelconques.",
      "Gérer plusieurs épaisseurs et facteurs K.",
      "Ajouter les dégagements de pli aux angles."],
 gamif="G-20 Erreur à débusquer + G-03 Compte à rebours", bareme="4 points développé, 3 points compensation, 3 points cotation."),

dict(id="C-12", titre="Imbrication et export de fabrication", them="C4 · Fabrication",
 ref="REF-113, REF-114, REF-087", niv="Expérimenté", duree=75, prereq="B-13, C-05",
 obj="Boucler la chaîne conception-fabrication avec un livrable machine.",
 comp="OpenNest, Rectangle, Sort List, Text Tag 3D, Write File, Area, Mass Addition",
 enonce="Imbrique les 46 pièces découpées fournies dans des plaques de 3 000 × 1 500 mm avec un espacement de 8 mm entre pièces et 15 mm de bord de plaque. Produis le plan de découpe repéré, le nombre de plaques et le taux de matière utile, puis exporte en DXF par plaque.",
 depart="46 contours de pièces internalisés.",
 att="Le plan d'imbrication, les indicateurs et un fichier DXF par plaque.",
 mode="NumericTolerance", tol="1 %", nb=38,
 etapes=["Préparer les contours : vérifier qu'ils sont fermés et plans avec un contrôle en amont.",
         "Construire le contour de plaque utile en retirant 15 mm sur chaque bord.",
         "Configurer OpenNest avec l'espacement de 8 mm et autoriser la rotation par pas de 90°.",
         "Lancer l'imbrication et récupérer les pièces placées et leur numéro de plaque.",
         "Compter les plaques avec Create Set sur les numéros de plaque.",
         "Calculer le taux de matière utile : aire des pièces divisée par aire des plaques utilisées.",
         "Repérer chaque pièce avec Text Tag 3D en conservant son repère d'origine.",
         "Grouper les pièces par plaque avec un arbre et écrire un DXF par branche."],
 pieges=["Repères perdus car non triés dans le même ordre que les pièces placées.",
         "Espacement configuré comme un décalage de contour au lieu d'une distance entre pièces.",
         "Pièces non fermées silencieusement ignorées par l'imbrication."],
 var=["Comparer avec le calepinage manuel de l'exercice B-13.",
      "Ajouter une contrainte de sens de fil.",
      "Générer le parcours d'outil approximatif et estimer le temps de découpe."],
 gamif="G-21 Golf de composants + G-23 Classement", bareme="4 points imbrication, 3 points indicateurs, 3 points export."),
]
