# -*- coding: utf-8 -*-
"""LOT A - Decouverte des composants natifs Grasshopper (Rhino 8) - niveau Debutant."""

LOT_A = [

# ---------------------------------------------- A1 Interface et flux de donnees
dict(id="A-01", titre="Premier flux de données", them="A1 · Interface, flux de données et paramètres",
 ref="REF-027, REF-028", niv="Débutant", duree=5, prereq="—",
 obj="Comprendre qu'un composant reçoit une donnée à gauche et la restitue à droite, et que le câble transporte cette donnée.",
 comp="Number Slider, Panel, Addition",
 enonce="Un Number Slider est posé sur le canvas. Ajoute un second Number Slider, additionne les deux valeurs et affiche le résultat dans un Panel. Règle les curseurs pour que la somme vaille exactement 42.",
 depart="Un Number Slider (0-100, valeur 17) déjà placé.",
 att="Un Panel affichant la valeur 42.",
 mode="SingleValue", tol="0", nb=4,
 etapes=["Poser un second Number Slider (menu Params > Input) et l'étendre de 0 à 100.",
         "Poser un composant Addition (Maths > Operators).",
         "Relier le premier slider sur l'entrée A, le second sur l'entrée B.",
         "Relier la sortie R vers un Panel (Params > Input > Panel).",
         "Ajuster les deux curseurs jusqu'à lire 42 dans le Panel."],
 pieges=["Relier deux câbles sur la même entrée A : Grasshopper additionne alors les deux valeurs sur A et laisse B vide.",
         "Slider réglé en entier alors que la cible demande une décimale."],
 var=["Remplacer Addition par Subtraction et viser -42.",
      "Ajouter un troisième slider avec Mass Addition."],
 gamif="G-02 Barre de progression", bareme="1 point si la valeur du Panel vaut 42."),

dict(id="A-02", titre="Construire un point par coordonnées", them="A1 · Interface, flux de données et paramètres",
 ref="REF-062", niv="Débutant", duree=6, prereq="A-01",
 obj="Distinguer un paramètre numérique d'une géométrie et construire un point à partir de trois nombres.",
 comp="Number Slider, Construct Point, Point",
 enonce="Construis le point de coordonnées X=30, Y=-15, Z=8 à l'aide de trois Number Sliders et d'un composant Construct Point. Le point doit être visible dans la vue Rhino.",
 depart="Canvas vide.",
 att="Un point unique aux coordonnées (30 ; -15 ; 8).",
 mode="GeometryTolerance", tol="0,01 mm", nb=4,
 etapes=["Poser trois Number Slider et les nommer X, Y et Z (double-clic sur le nom).",
         "Régler les bornes de Y de -50 à 50 pour autoriser la valeur négative.",
         "Poser Construct Point (Vector > Point).",
         "Relier chaque slider sur l'entrée correspondante X, Y, Z.",
         "Vérifier l'aperçu du point dans la vue Rhino."],
 pieges=["Slider borné à 0-100 : impossible d'atteindre -15.",
         "Confondre Construct Point et Deconstruct Point."],
 var=["Ajouter un second point et tracer la Line entre les deux.",
      "Remplacer les sliders par un unique Panel multiligne."],
 gamif="G-26 Feedback visuel immédiat", bareme="1 point si le point est à moins de 0,01 mm de la cible."),

dict(id="A-03", titre="Internaliser une donnée", them="A1 · Interface, flux de données et paramètres",
 ref="REF-027", niv="Débutant", duree=6, prereq="A-02",
 obj="Comprendre la différence entre une donnée calculée en amont et une donnée figée dans un paramètre.",
 comp="Point (paramètre), Set One Point, Internalise data",
 enonce="Le point vert est produit par un Construct Point. Fige-le dans un paramètre Point autonome puis supprime la chaîne amont : le point doit rester affiché.",
 depart="Un Construct Point alimenté par trois sliders.",
 att="Un paramètre Point contenant une donnée internalisée, la chaîne amont supprimée.",
 mode="GeometryTolerance", tol="0,01 mm", nb=1,
 etapes=["Poser un paramètre Point (Params > Geometry > Point).",
         "Relier la sortie du Construct Point vers ce paramètre.",
         "Clic droit sur le paramètre > Internalise data.",
         "Supprimer le Construct Point et les trois sliders.",
         "Vérifier que le point reste affiché : la donnée est désormais portée par le paramètre."],
 pieges=["Internaliser avant que le paramètre ait reçu la donnée : le paramètre reste vide.",
         "Confondre Internalise data et Set One Point (saisie manuelle dans Rhino)."],
 var=["Internaliser une courbe dessinée dans Rhino.",
      "Comparer la taille du fichier .gh avant et après internalisation d'un maillage."],
 gamif="G-19 Le composant mystère", bareme="1 point si le point subsiste sans chaîne amont."),

dict(id="A-04", titre="Référencer et cuire de la géométrie Rhino", them="A1 · Interface, flux de données et paramètres",
 ref="REF-026", niv="Débutant", duree=8, prereq="A-03",
 obj="Faire circuler la géométrie entre Rhino et Grasshopper dans les deux sens.",
 comp="Curve (paramètre), Geometry Pipeline, Bake (menu contextuel)",
 enonce="Le fichier Rhino contient trois cercles sur le calque « CERCLES ». Récupère-les dans Grasshopper sans les sélectionner un par un, décale-les de 50 mm en Z, puis cuis le résultat sur le calque « COPIES ».",
 depart="Fichier 3DM joint contenant trois cercles sur le calque CERCLES.",
 att="Trois cercles cuits sur le calque COPIES, décalés de 50 mm en Z.",
 mode="GeometryTolerance", tol="0,1 mm", nb=4,
 etapes=["Poser Geometry Pipeline (Params > Util) et saisir CERCLES dans le champ Layer.",
         "Vérifier que trois courbes sont captées (survol de la sortie).",
         "Poser Unit Z (Vector > Vector) et un slider réglé sur 50.",
         "Poser Move et relier la géométrie et le vecteur.",
         "Clic droit sur Move > Bake, choisir le calque COPIES."],
 pieges=["Le Geometry Pipeline est sensible à la casse du nom de calque.",
         "Oublier de multiplier Unit Z par la valeur du slider : le décalage vaut 1 mm."],
 var=["Filtrer le Pipeline par type de géométrie plutôt que par calque.",
      "Utiliser Elefront pour cuire avec des attributs."],
 gamif="G-05 Badges et trophées", bareme="1 point si les trois cercles sont cuits au bon niveau."),

dict(id="A-05", titre="Lire ce qui circule dans un câble", them="A1 · Interface, flux de données et paramètres",
 ref="REF-027, REF-028", niv="Débutant", duree=5, prereq="A-01",
 obj="Savoir inspecter un flux : nombre d'éléments, type et structure.",
 comp="Panel, Param Viewer, Number, Quick Graph",
 enonce="Un câble transporte une donnée inconnue. Sans modifier le graphe, indique dans un Panel le nombre d'éléments qu'il transporte.",
 depart="Un composant amont masqué produisant une liste de 12 nombres.",
 att="Un Panel affichant 12.",
 mode="SingleValue", tol="0", nb=2,
 etapes=["Poser un Param Viewer et le brancher sur le câble à inspecter.",
         "Basculer le Param Viewer en mode texte pour lire la structure.",
         "Poser List Length (Sets > List) sur le même câble.",
         "Relier la sortie L vers un Panel."],
 pieges=["Confondre le nombre de branches et le nombre d'éléments.",
         "Lire la valeur affichée par le Panel plutôt que le nombre de lignes."],
 var=["Ajouter un Tree Statistics pour lire les chemins.",
      "Comparer List Length avant et après un Flatten."],
 gamif="G-17 Quiz éclair", bareme="1 point si le Panel affiche 12."),

# ---------------------------------------------------- A2 Types et conversions
dict(id="A-06", titre="Conversion implicite Number vers Integer", them="A2 · Types, conversion et valeurs",
 ref="REF-040", niv="Débutant", duree=6, prereq="A-01",
 obj="Observer qu'un composant attendant un entier arrondit silencieusement une valeur décimale.",
 comp="Number Slider, Series, Panel",
 enonce="Le slider vaut 4,6. Il alimente l'entrée Count d'un Series qui attend un entier. Combien d'éléments la série contient-elle ? Affiche le nombre dans un Panel et explique la règle appliquée.",
 depart="Un Number Slider décimal réglé sur 4,6 relié à Series.",
 att="Un Panel affichant 5 (arrondi au plus proche).",
 mode="SingleValue", tol="0", nb=3,
 etapes=["Brancher un List Length sur la sortie de Series.",
         "Relier vers un Panel : la série contient 5 éléments.",
         "Faire varier le slider entre 4,4 et 4,6 pour observer la bascule.",
         "Conclure : Grasshopper arrondit au plus proche, il ne tronque pas."],
 pieges=["Supposer une troncature (4,6 donnerait 4) : c'est faux.",
         "Ne pas remarquer que le survol de l'entrée affiche déjà la valeur convertie."],
 var=["Refaire l'essai avec 4,5 puis 5,5 pour observer la règle de l'arrondi.",
      "Insérer un Round explicite pour rendre le comportement visible."],
 gamif="G-18 Vrai / Faux à élimination", bareme="1 point pour la valeur, 1 point pour la règle énoncée en QCM."),

dict(id="A-07", titre="Quand la conversion échoue", them="A2 · Types, conversion et valeurs",
 ref="REF-041", niv="Débutant", duree=6, prereq="A-06",
 obj="Reconnaître un composant en échec et lire le message d'erreur.",
 comp="Panel, Addition, Number",
 enonce="Un Panel contenant le texte « douze » alimente une Addition. Qu'affiche la sortie ? Corrige le montage pour que l'addition renvoie 15 sans supprimer le Panel.",
 depart="Un Panel contenant « douze » relié à l'entrée A d'une Addition, un slider à 3 sur B.",
 att="Composant en orange puis, après correction, résultat 15.",
 mode="SingleValue", tol="0", nb=4,
 etapes=["Survoler le composant orange pour lire l'avertissement de conversion.",
         "Remplacer le contenu du Panel par 12 (valeur numérique).",
         "Vérifier que le composant redevient normal et affiche 15.",
         "Retenir : un texte non numérique produit une valeur nulle, pas un zéro."],
 pieges=["Croire qu'un échec de conversion produit 0 : il produit une valeur nulle.",
         "Confondre un composant orange (avertissement) et rouge (erreur)."],
 var=["Tester « 12 » entre guillemets, « 12,5 » et « 12.5 » pour observer le séparateur décimal.",
      "Insérer un Text To Number explicite."],
 gamif="G-20 Erreur volontaire à débusquer", bareme="1 point pour le diagnostic, 1 point pour la correction."),

dict(id="A-08", titre="Booléen et nombre", them="A2 · Types, conversion et valeurs",
 ref="REF-040, REF-059", niv="Débutant", duree=5, prereq="A-06",
 obj="Comprendre l'équivalence True/1 et False/0 et son usage pour compter.",
 comp="Boolean Toggle, Mass Addition, Larger Than",
 enonce="Une liste de 10 nombres est comparée à la valeur 5. Compte combien d'éléments sont strictement supérieurs à 5, sans utiliser de composant de filtrage.",
 depart="Une liste de 10 nombres internalisée et un slider réglé sur 5.",
 att="Un Panel affichant le nombre d'éléments supérieurs à 5.",
 mode="SingleValue", tol="0", nb=4,
 etapes=["Poser Larger Than (Maths > Operators) : liste sur A, slider sur B.",
         "La sortie est une liste de booléens.",
         "Poser Mass Addition (Maths > Operators) sur cette liste de booléens.",
         "Le total correspond au nombre de valeurs True."],
 pieges=["Brancher Mass Addition sur la liste d'origine au lieu des booléens.",
         "Utiliser Larger Than au lieu de Larger Than or Equal quand l'énoncé dit « au moins »."],
 var=["Compter les valeurs comprises entre deux bornes avec Gate And.",
      "Afficher le pourcentage plutôt que le compte."],
 gamif="G-01 Score visible", bareme="1 point si le compte est exact."),

dict(id="A-09", titre="Valeur nulle et propagation", them="A2 · Types, conversion et valeurs",
 ref="REF-055", niv="Débutant", duree=7, prereq="A-07",
 obj="Repérer une valeur nulle dans une liste et mesurer son effet en aval.",
 comp="Panel, Null Item, Clean Tree, List Length",
 enonce="Une liste de 8 nombres contient deux valeurs nulles. Nettoie la liste et indique dans un Panel combien d'éléments valides subsistent.",
 depart="Une liste de 8 éléments internalisée dont 2 nulles.",
 att="Un Panel affichant 6.",
 mode="SingleValue", tol="0", nb=3,
 etapes=["Brancher Null Item (Sets > Tree) pour localiser les nulles.",
         "Poser Clean Tree avec Remove Nulls activé.",
         "Brancher List Length sur la sortie nettoyée.",
         "Relier vers un Panel : 6 éléments valides."],
 pieges=["Un Panel affiche une ligne vide pour une valeur nulle : elle passe inaperçue.",
         "Clean Tree supprime aussi les branches vides si l'option est cochée."],
 var=["Remplacer les nulles par une valeur par défaut avec Replace Nulls.",
      "Observer la propagation d'une nulle à travers une Addition."],
 gamif="G-16 Chasse au trésor sur le canvas", bareme="1 point si le Panel affiche 6."),

# ------------------------------------------------------------------ A3 Listes
dict(id="A-10", titre="Series et Range", them="A3 · Listes",
 ref="REF-043, REF-047", niv="Débutant", duree=7, prereq="A-01",
 obj="Générer une suite de nombres et distinguer les deux logiques de génération.",
 comp="Series, Range, Panel",
 enonce="Produis avec Series la suite 10, 15, 20, 25, 30 puis, avec Range, la même suite. Affiche les deux dans deux Panels distincts.",
 depart="Canvas vide.",
 att="Deux Panels contenant chacun 10, 15, 20, 25, 30.",
 mode="ExactOrderedList", tol="0", nb=5,
 etapes=["Series : Start = 10, Step = 5, Count = 5.",
         "Range : Domain = 10 To 30 (Construct Domain), Steps = 4.",
         "Relier chaque sortie vers un Panel.",
         "Retenir : Series raisonne en pas et nombre d'éléments, Range en domaine et subdivisions."],
 pieges=["Range avec Steps = 5 produit 6 valeurs, pas 5.",
         "Oublier Construct Domain et saisir le domaine dans un Panel."],
 var=["Produire une suite décroissante avec un pas négatif.",
      "Générer 5 valeurs entre 0 et 1 pour piloter un paramètre normalisé."],
 gamif="G-07 Étoiles de performance", bareme="2 points : 1 par suite correcte."),

dict(id="A-11", titre="List Item et indexation", them="A3 · Listes",
 ref="REF-042", niv="Débutant", duree=6, prereq="A-10",
 obj="Lire un élément par son index et comprendre l'indexation à partir de zéro.",
 comp="List Item, Series, Panel",
 enonce="La liste contient 10 lettres de A à J. Extrais la lettre D, puis la dernière lettre de la liste sans coder son index en dur.",
 depart="Une liste de 10 textes internalisée.",
 att="Deux Panels : l'un affiche D, l'autre J.",
 mode="ExactOrderedList", tol="0", nb=5,
 etapes=["Poser List Item et régler l'index à 3 : la lettre D sort (le premier élément porte l'index 0).",
         "Pour la dernière lettre, poser List Length puis soustraire 1.",
         "Relier ce résultat sur l'index d'un second List Item.",
         "Alternative : activer l'index négatif -1 sur List Item (clic droit > Wrap)."],
 pieges=["Saisir l'index 4 pour la lettre D.",
         "Coder 9 en dur : le montage casse si la liste change de taille."],
 var=["Extraire simultanément les index 0, 4 et 9 en branchant une liste d'index.",
      "Extraire un élément sur deux avec Cull Index."],
 gamif="G-12 Memory", bareme="2 points : 1 par extraction correcte."),

dict(id="A-12", titre="Longueur et bornes d'une liste", them="A3 · Listes",
 ref="REF-043", niv="Débutant", duree=5, prereq="A-11",
 obj="Mesurer une liste et en extraire les valeurs extrêmes.",
 comp="List Length, Bounds, Deconstruct Domain, Sort List",
 enonce="Pour la liste fournie, affiche dans un même Panel le nombre d'éléments, la valeur minimale et la valeur maximale, dans cet ordre.",
 depart="Une liste de 15 nombres non triés internalisée.",
 att="Un Panel de trois lignes : effectif, minimum, maximum.",
 mode="ExactOrderedList", tol="0", nb=5,
 etapes=["Poser List Length pour l'effectif.",
         "Poser Bounds (Maths > Domain) puis Deconstruct Domain pour obtenir min et max.",
         "Assembler les trois valeurs avec Merge dans le bon ordre.",
         "Relier vers un Panel."],
 pieges=["Merge respecte l'ordre de branchement des entrées : vérifier l'ordre.",
         "Utiliser Sort List et lire le premier et le dernier élément fonctionne aussi mais coûte plus de composants."],
 var=["Ajouter la moyenne avec Average.",
      "Afficher l'index du minimum avec Sort List et List Item."],
 gamif="G-21 Golf de composants", bareme="1 point si les trois valeurs sont exactes et dans l'ordre."),

dict(id="A-13", titre="Trier une liste avec une clé", them="A3 · Listes",
 ref="REF-044, REF-047", niv="Débutant", duree=8, prereq="A-12",
 obj="Trier une liste secondaire selon les valeurs d'une liste de clés.",
 comp="Sort List, Reverse List, Panel",
 enonce="Six pièces portent un nom et une longueur. Classe les noms de la pièce la plus longue à la plus courte.",
 depart="Deux listes internalisées : 6 noms et 6 longueurs.",
 att="Un Panel listant les noms par longueur décroissante.",
 mode="ExactOrderedList", tol="0", nb=4,
 etapes=["Poser Sort List : longueurs sur Keys, noms sur Values A.",
         "La sortie A est triée par longueur croissante.",
         "Poser Reverse List sur la sortie A pour obtenir l'ordre décroissant.",
         "Relier vers un Panel."],
 pieges=["Brancher les noms sur Keys : le tri se fait alors par ordre alphabétique.",
         "Oublier que Sort List renvoie aussi les clés triées sur la sortie K."],
 var=["Trier selon deux critères successifs.",
      "Trier des points par distance à un point de référence."],
 gamif="G-08 Combo / série", bareme="1 point si l'ordre exact est respecté."),

dict(id="A-14", titre="Filtrer avec Cull Pattern", them="A3 · Listes",
 ref="REF-045", niv="Débutant", duree=7, prereq="A-13",
 obj="Éliminer des éléments selon un motif booléen répétitif.",
 comp="Cull Pattern, Boolean Toggle, Panel",
 enonce="La liste contient 12 nombres. Conserve un élément sur trois en commençant par le premier.",
 depart="Une liste de 12 nombres internalisée.",
 att="Une liste de 4 éléments : index 0, 3, 6 et 9.",
 mode="ExactOrderedList", tol="0", nb=3,
 etapes=["Poser Cull Pattern (Sets > Sequence).",
         "Dans un Panel, saisir le motif True, False, False sur trois lignes.",
         "Relier le Panel sur l'entrée Pattern et la liste sur List.",
         "Le motif se répète cycliquement sur toute la liste."],
 pieges=["Saisir le motif sur une seule ligne : Grasshopper lit un seul élément.",
         "Confondre Cull Pattern (motif cyclique) et Cull Index (index explicites)."],
 var=["Inverser le motif pour conserver les deux autres tiers.",
      "Piloter le motif par une comparaison numérique."],
 gamif="G-13 Casino — motifs assortis", bareme="1 point si les 4 bons éléments sont conservés."),

dict(id="A-15", titre="Répartir avec Dispatch", them="A3 · Listes",
 ref="REF-045, REF-061", niv="Débutant", duree=7, prereq="A-14",
 obj="Séparer une liste en deux sorties selon une condition.",
 comp="Dispatch, Larger Than, Panel",
 enonce="Sépare la liste de 20 nombres en deux : d'un côté les valeurs supérieures ou égales à 50, de l'autre les valeurs inférieures.",
 depart="Une liste de 20 nombres internalisée.",
 att="Deux Panels contenant respectivement les valeurs ≥ 50 et < 50.",
 mode="SetEquality", tol="0", nb=5,
 etapes=["Poser Larger Than or Equal : liste sur A, valeur 50 sur B.",
         "Poser Dispatch : liste sur List, booléens sur Pattern.",
         "La sortie A reçoit les True, la sortie B les False.",
         "Relier chaque sortie vers un Panel."],
 pieges=["Inverser les sorties A et B.",
         "Utiliser Larger Than strict alors que l'énoncé inclut 50."],
 var=["Répartir des points selon leur coordonnée Z.",
      "Répartir en trois catégories en chaînant deux Dispatch."],
 gamif="G-15 Dessin à compléter", bareme="1 point par sortie correcte."),

dict(id="A-16", titre="Décaler et inverser une liste", them="A3 · Listes",
 ref="REF-046", niv="Débutant", duree=6, prereq="A-11",
 obj="Faire tourner l'ordre des éléments d'une liste, opération clé pour relier des points en polygone.",
 comp="Shift List, Reverse List, Line",
 enonce="Huit points forment un octogone. Trace les huit segments qui relient chaque point au suivant, le dernier revenant au premier, en n'utilisant qu'un seul composant Line.",
 depart="Une liste de 8 points internalisée, disposés en cercle.",
 att="Huit segments fermant le polygone.",
 mode="GeometryTolerance", tol="0,1 mm", nb=3,
 etapes=["Poser Shift List avec un décalage de 1 et l'option Wrap activée.",
         "Poser Line : liste d'origine sur A, liste décalée sur B.",
         "Les huit segments se tracent, le huitième reliant le dernier point au premier.",
         "Désactiver Wrap pour observer qu'il ne reste que sept segments."],
 pieges=["Wrap désactivé : le polygone reste ouvert.",
         "Utiliser Polyline avec l'option Closed masque le mécanisme visé par l'exercice."],
 var=["Décaler de 2 pour obtenir les diagonales.",
      "Comparer avec PolyLine fermée."],
 gamif="G-25 Animation de la solution", bareme="1 point si les 8 segments sont produits."),

dict(id="A-17", titre="Fusionner et entrelacer", them="A3 · Listes",
 ref="REF-042", niv="Débutant", duree=6, prereq="A-13",
 obj="Assembler plusieurs listes en une seule, bout à bout ou en alternance.",
 comp="Merge, Weave, Panel",
 enonce="Deux listes contiennent respectivement A, B, C et 1, 2, 3. Produis la liste A, 1, B, 2, C, 3.",
 depart="Deux listes de 3 éléments internalisées.",
 att="Un Panel affichant A, 1, B, 2, C, 3.",
 mode="ExactOrderedList", tol="0", nb=3,
 etapes=["Poser Weave (Sets > List).",
         "Relier la première liste sur Stream 0, la seconde sur Stream 1.",
         "Laisser le motif par défaut 0, 1 : l'alternance est automatique.",
         "Comparer avec Merge qui produirait A, B, C, 1, 2, 3."],
 pieges=["Confondre Weave (alternance) et Merge (concaténation).",
         "Motif de tissage personnalisé mal renseigné."],
 var=["Tisser trois listes avec un motif 0, 1, 2.",
      "Reconstituer les deux listes d'origine avec Cull Pattern."],
 gamif="G-11 Mots croisés de composants", bareme="1 point si l'ordre exact est obtenu."),

dict(id="A-18", titre="Extraire une portion de liste", them="A3 · Listes",
 ref="REF-042, REF-043", niv="Débutant", duree=6, prereq="A-12",
 obj="Prélever une sous-liste par domaine d'index.",
 comp="Sub List, Construct Domain, Split List",
 enonce="La liste contient 20 éléments. Extrais les éléments d'index 5 à 12 inclus.",
 depart="Une liste de 20 nombres internalisée.",
 att="Une liste de 8 éléments.",
 mode="ExactOrderedList", tol="0", nb=4,
 etapes=["Poser Construct Domain avec A = 5 et B = 12.",
         "Poser Sub List : liste sur L, domaine sur D.",
         "Vérifier avec List Length que la sous-liste contient 8 éléments.",
         "Retenir : le domaine est inclusif aux deux bornes."],
 pieges=["Croire la borne haute exclusive : on obtiendrait 7 éléments.",
         "Saisir le domaine dans un Panel sous la forme « 5 to 12 » sans Construct Domain."],
 var=["Couper la liste en deux avec Split List.",
      "Extraire les 5 derniers éléments quelle que soit la taille de la liste."],
 gamif="G-03 Compte à rebours", bareme="1 point si les 8 bons éléments sortent."),

# ------------------------------------------------------- A4 Arbres de donnees
dict(id="A-19", titre="Lire un chemin d'arbre", them="A4 · Arbres de données",
 ref="REF-048, REF-051", niv="Débutant", duree=7, prereq="A-05",
 obj="Identifier branches et chemins et savoir les lire dans l'interface.",
 comp="Param Viewer, Tree Statistics, Panel",
 enonce="L'arbre fourni contient plusieurs branches. Indique dans un Panel le nombre de branches, puis le chemin exact de la troisième branche.",
 depart="Un arbre internalisé de 4 branches contenant chacune 3 éléments.",
 att="Un Panel affichant 4 puis le chemin {0;2}.",
 mode="ExactOrderedList", tol="0", nb=4,
 etapes=["Poser Tree Statistics (Sets > Tree) : la sortie P donne la liste des chemins.",
         "Brancher List Length sur P pour obtenir le nombre de branches.",
         "Poser List Item sur P avec l'index 2 pour lire le troisième chemin.",
         "Relier les deux résultats vers un Panel."],
 pieges=["Confondre nombre de branches et nombre total d'éléments.",
         "Compter les branches à partir de 1."],
 var=["Afficher le nombre d'éléments par branche avec la sortie C.",
      "Comparer l'affichage du Param Viewer en mode graphe et en mode texte."],
 gamif="G-31 Carte de progression", bareme="1 point par réponse correcte."),

dict(id="A-20", titre="Graft et Flatten", them="A4 · Arbres de données",
 ref="REF-049, REF-052", niv="Débutant", duree=8, prereq="A-19",
 obj="Transformer la structure d'un flux et en mesurer l'effet sur le résultat produit.",
 comp="Graft, Flatten, Line, Param Viewer",
 enonce="Trois points sont reliés à trois autres points par un composant Line. Sans Graft, on obtient 3 segments. Ajoute un Graft sur l'une des entrées pour obtenir les 9 segments de toutes les combinaisons possibles.",
 depart="Deux listes de 3 points internalisées, reliées par un Line.",
 att="Neuf segments.",
 mode="GeometryTolerance", tol="0,1 mm", nb=3,
 etapes=["Vérifier l'état initial : 3 segments seulement (correspondance un à un).",
         "Clic droit sur l'entrée A du Line > Graft : chaque point part dans sa propre branche.",
         "Grasshopper croise alors chaque branche de A avec la liste complète de B : 9 segments.",
         "Ajouter un Flatten en sortie et observer que les 9 segments retombent dans une seule liste."],
 pieges=["Grafter les deux entrées : on retombe à 3 segments.",
         "Confondre Graft (éclate en branches) et Flatten (aplatit)."],
 var=["Obtenir le même résultat avec Cross Reference.",
      "Grafter une liste de courbes avant un Divide Curve."],
 gamif="G-22 Boss de fin de chapitre", bareme="1 point si 9 segments sont produits."),

dict(id="A-21", titre="Nettoyer une structure", them="A4 · Arbres de données",
 ref="REF-050", niv="Débutant", duree=7, prereq="A-20",
 obj="Supprimer les niveaux de branche inutiles sans écraser la structure utile.",
 comp="Simplify Tree, Trim Tree, Param Viewer",
 enonce="L'arbre fourni porte des chemins de la forme {0;0;0;2}. Ramène-le à des chemins à un seul niveau sans perdre le regroupement des éléments.",
 depart="Un arbre internalisé de chemins {0;0;0;0} à {0;0;0;3}.",
 att="Un arbre de 4 branches aux chemins {0} à {3}.",
 mode="SetEquality", tol="0", nb=2,
 etapes=["Brancher un Param Viewer pour lire les chemins de départ.",
         "Poser Simplify Tree : les niveaux communs à toutes les branches sont supprimés.",
         "Vérifier les nouveaux chemins dans le Param Viewer.",
         "Retenir : Trim Tree supprime le dernier niveau, Simplify supprime les niveaux redondants."],
 pieges=["Utiliser Flatten : la structure disparaît complètement.",
         "Trim Tree avec une profondeur trop grande fusionne des branches utiles."],
 var=["Comparer Simplify et Trim Tree sur le même arbre.",
      "Reconstruire un chemin cible avec Path Mapper."],
 gamif="G-30 Mode coopératif", bareme="1 point si les chemins finaux sont {0} à {3}."),

dict(id="A-22", titre="Construire un arbre", them="A4 · Arbres de données",
 ref="REF-048, REF-051", niv="Débutant", duree=8, prereq="A-21",
 obj="Assembler plusieurs listes en un arbre maîtrisé et le redécomposer.",
 comp="Entwine, Explode Tree, Merge",
 enonce="Trois listes de longueurs différentes doivent former un arbre de trois branches, puis être réextraites individuellement.",
 depart="Trois listes internalisées de 2, 5 et 3 éléments.",
 att="Un arbre de 3 branches puis trois sorties séparées identiques aux listes d'origine.",
 mode="SetEquality", tol="0", nb=3,
 etapes=["Poser Entwine et brancher les trois listes sur trois entrées.",
         "Vérifier au Param Viewer : trois branches de 2, 5 et 3 éléments.",
         "Poser Explode Tree en aval et zoomer pour faire apparaître les sorties.",
         "Chaque sortie restitue la liste d'origine."],
 pieges=["Merge à la place d'Entwine : les trois listes fusionnent en une seule.",
         "Explode Tree n'affiche ses sorties qu'après un zoom suffisant."],
 var=["Entwiner des géométries de types différents.",
      "Renommer les chemins produits avec Path Mapper."],
 gamif="G-14 Puzzle de câblage", bareme="1 point pour l'arbre, 1 point pour la décomposition."),

dict(id="A-23", titre="Renommer les chemins avec Path Mapper", them="A4 · Arbres de données",
 ref="REF-050", niv="Débutant", duree=9, prereq="A-22",
 obj="Réécrire les chemins d'un arbre pour préparer une mise en correspondance.",
 comp="Path Mapper, Param Viewer",
 enonce="L'arbre porte les chemins {0;0} à {2;3}. Inverse les deux niveaux pour obtenir {0;0} à {3;2}.",
 depart="Un arbre internalisé de 12 branches à deux niveaux.",
 att="Un arbre dont les deux niveaux de chemin sont permutés.",
 mode="SetEquality", tol="0", nb=1,
 etapes=["Poser Path Mapper et double-cliquer pour ouvrir l'éditeur.",
         "Saisir le masque source {A;B}.",
         "Saisir le masque cible {B;A}.",
         "Valider et vérifier les chemins au Param Viewer."],
 pieges=["Oublier les accolades dans les masques.",
         "Utiliser des lettres différentes entre source et cible."],
 var=["Fusionner deux niveaux avec le masque {A;B} vers {A}.",
      "Insérer un niveau constant avec {A} vers {0;A}."],
 gamif="G-32 Indices payants", bareme="1 point si les chemins sont permutés."),

# ---------------------------------------------- A5 Comportements implicites
dict(id="A-24", titre="Correspondance par défaut", them="A5 · Comportements implicites",
 ref="REF-053", niv="Débutant", duree=7, prereq="A-10",
 obj="Observer la correspondance appliquée par défaut lorsque deux listes de tailles différentes entrent dans un même composant.",
 comp="Addition, Series, List Length, Panel",
 enonce="Une liste de 10 nombres et une liste de 4 nombres entrent dans une même Addition. Combien de résultats sortent ? Affiche le compte dans un Panel, puis explique comment les 6 derniers ont été calculés.",
 depart="Deux listes internalisées de 10 et 4 éléments reliées à une Addition.",
 att="Un Panel affichant 10 : la liste courte est complétée par répétition de son dernier élément.",
 mode="SingleValue", tol="0", nb=3,
 etapes=["Brancher List Length sur la sortie de l'Addition.",
         "Relier vers un Panel : 10 résultats, et non 4.",
         "Comparer les 6 derniers résultats à la liste longue : ils ont tous été additionnés au MÊME nombre, le dernier de la liste courte.",
         "Constater qu'aucun avertissement n'est émis : ce complètement est silencieux.",
         "Retenir : le comportement par défaut est la correspondance sur la liste la plus longue, la liste courte étant prolongée par son dernier élément."],
 pieges=["Croire que Grasshopper tronque sur la liste la plus courte : ce comportement existe (Shortest List) mais doit être demandé explicitement par clic droit sur le composant.",
         "Ne pas vérifier la longueur et supposer que chaque paire a bien été formée une seule fois.",
         "Ne pas voir que les 6 derniers résultats reposent sur une valeur répétée, donc sur une donnée fabriquée."],
 var=["Basculer le composant en Shortest List par clic droit et vérifier que l'on retombe à 4 résultats.",
      "Reproduire le cas avec des points et un Move : 6 points sont déplacés du même vecteur."],
 gamif="G-09 Récompense cachée", bareme="1 point si le Panel affiche 4."),

dict(id="A-25", titre="Longest List et Cross Reference", them="A5 · Comportements implicites",
 ref="REF-054", niv="Débutant", duree=8, prereq="A-24",
 obj="Choisir volontairement un mode de correspondance et en mesurer l'effet.",
 comp="Longest List, Cross Reference, Addition, List Length",
 enonce="Avec les mêmes listes de 10 et 4 éléments, produis successivement 10 résultats puis 40 résultats, en indiquant à chaque fois le composant employé.",
 depart="Deux listes internalisées de 10 et 4 éléments.",
 att="Deux Panels affichant 10 puis 40.",
 mode="ExactOrderedList", tol="0", nb=6,
 etapes=["Insérer Longest List (Sets > List) en amont de l'Addition : la liste courte est complétée par son dernier élément, 10 résultats.",
         "Insérer Cross Reference à la place : chaque élément de A est croisé avec chaque élément de B, 40 résultats.",
         "Mesurer les deux sorties avec List Length.",
         "Comparer avec le Graft de l'exercice A-20 qui produit le même croisement sous forme d'arbre."],
 pieges=["Cross Reference propose plusieurs variantes (Holistic, Diagonal) dans son menu contextuel.",
         "Longest List complète par répétition du dernier élément, pas par des zéros."],
 var=["Obtenir 40 résultats par Graft plutôt que par Cross Reference et comparer les structures.",
      "Tester le mode Diagonal de Cross Reference."],
 gamif="G-23 Duel et classement", bareme="1 point par valeur correcte."),

dict(id="A-26", titre="Ordre d'évaluation et recalcul", them="A5 · Comportements implicites",
 ref="REF-056, REF-090", niv="Débutant", duree=6, prereq="A-24",
 obj="Comprendre que Grasshopper recalcule en cascade selon les dépendances, sans ordre imposé par la position sur le canvas.",
 comp="Number Slider, Timer, Panel, Profiler (widget)",
 enonce="Deux branches indépendantes du graphe produisent chacune un résultat. Dans quel ordre sont-elles évaluées ? Réponds par QCM et justifie en modifiant un seul slider.",
 depart="Un graphe à deux branches indépendantes.",
 att="Réponse QCM : l'ordre dépend du graphe de dépendances, pas de la position sur le canvas.",
 mode="Conceptuel (QCM)", tol="—", nb=0,
 etapes=["Activer le widget Profiler (menu Display) pour lire les temps par composant.",
         "Modifier un slider et observer que seule la branche dépendante se recalcule.",
         "Déplacer physiquement un composant : aucun changement d'ordre.",
         "Conclure : l'ordre suit les dépendances de données."],
 pieges=["Croire que la position gauche-droite impose l'ordre d'exécution.",
         "Confondre ordre d'évaluation et ordre d'affichage."],
 var=["Introduire un Timer et observer le recalcul cyclique.",
      "Utiliser Metahopper pour visualiser le graphe de dépendances."],
 gamif="G-17 Quiz éclair", bareme="1 point pour la bonne réponse au QCM."),

# ------------------------------------------------------------------- A6 Texte
dict(id="A-27", titre="Construire une chaîne de caractères", them="A6 · Outils de texte",
 ref="REF-057", niv="Débutant", duree=6, prereq="A-11",
 obj="Assembler texte et valeurs numériques en un libellé exploitable.",
 comp="Concatenate, Text Join, Panel",
 enonce="Pour chacune des 5 pièces, produis le libellé « PIECE-01 : 1250 mm » à partir de la liste des numéros et de la liste des longueurs.",
 depart="Deux listes internalisées : 5 numéros et 5 longueurs.",
 att="Une liste de 5 libellés au format demandé.",
 mode="ExactOrderedList", tol="0", nb=6,
 etapes=["Formater le numéro sur deux chiffres avec Format (masque {0:00}).",
         "Poser Concatenate et brancher successivement PIECE-, le numéro formaté, le séparateur, la longueur et l'unité.",
         "Zoomer sur Concatenate pour ajouter des entrées si nécessaire.",
         "Relier vers un Panel et contrôler les espaces."],
 pieges=["Oublier les espaces autour du deux-points.",
         "Concaténer un nombre décimal sans le formater : 1250,0 s'affiche."],
 var=["Produire un libellé multiligne avec Text Join et un séparateur retour ligne.",
      "Utiliser ces libellés comme texte de cotation dans Rhino."],
 gamif="G-11 Mots croisés de composants", bareme="1 point si les 5 libellés sont exacts."),

dict(id="A-28", titre="Découper et remplacer du texte", them="A6 · Outils de texte",
 ref="REF-058", niv="Débutant", duree=7, prereq="A-27",
 obj="Extraire une information d'une chaîne structurée.",
 comp="Text Split, Replace Text, Text Case, Trim",
 enonce="À partir des références « MEUB-A12-CHENE », extrais uniquement le code central (A12) et convertis-le en minuscules.",
 depart="Une liste de 6 références internalisée.",
 att="Une liste de 6 codes en minuscules (a12, b07, …).",
 mode="ExactOrderedList", tol="0", nb=4,
 etapes=["Poser Text Split avec le séparateur - (tiret).",
         "La sortie est un arbre : chaque référence donne une branche de 3 fragments.",
         "Poser List Item avec l'index 1 pour prendre le fragment central de chaque branche.",
         "Poser Text Case en mode Lower."],
 pieges=["Oublier que Text Split produit un arbre et non une liste plate.",
         "Espaces parasites : appliquer Trim avant le découpage."],
 var=["Remplacer le matériau par un autre avec Replace Text.",
      "Reconstituer la référence complète après modification."],
 gamif="G-19 Le composant mystère", bareme="1 point si les 6 codes sont exacts."),

# ----------------------------------------------------------------- A7 Logique
dict(id="A-29", titre="Comparer deux valeurs", them="A7 · Portes logiques",
 ref="REF-059", niv="Débutant", duree=5, prereq="A-08",
 obj="Produire un booléen à partir d'une comparaison numérique.",
 comp="Equality, Larger Than, Smaller Than, Similarity",
 enonce="Compare les valeurs 0,1 + 0,2 et 0,3 avec Equality. Le résultat est-il True ? Corrige le montage pour qu'il le devienne.",
 depart="Deux Number Slider et une Equality.",
 att="Un booléen True obtenu par une comparaison avec tolérance.",
 mode="SingleValue", tol="—", nb=4,
 etapes=["Constater que Equality renvoie False en raison de la représentation des décimaux.",
         "Remplacer Equality par Similarity (Maths > Operators).",
         "Régler l'entrée de tolérance sur 0,001.",
         "La sortie passe à True."],
 pieges=["Comparer des flottants avec une égalité stricte.",
         "Confondre la tolérance de Similarity et la tolérance du document Rhino."],
 var=["Comparer deux points avec une distance et un seuil.",
      "Comparer deux textes avec Equality."],
 gamif="G-18 Vrai / Faux à élimination", bareme="1 point si la sortie vaut True."),

dict(id="A-30", titre="Combiner plusieurs conditions", them="A7 · Portes logiques",
 ref="REF-060", niv="Débutant", duree=7, prereq="A-29",
 obj="Assembler plusieurs tests en une décision unique.",
 comp="Gate And, Gate Or, Gate Not, Larger Than, Smaller Than",
 enonce="Parmi 20 pièces, identifie celles dont la longueur est comprise entre 500 et 1500 mm inclus. Le résultat doit être une liste de booléens.",
 depart="Une liste de 20 longueurs internalisée.",
 att="Une liste de 20 booléens.",
 mode="SetEquality", tol="0", nb=5,
 etapes=["Poser Larger Than or Equal avec 500 sur B.",
         "Poser Smaller Than or Equal avec 1500 sur B.",
         "Poser Gate And et brancher les deux listes de booléens.",
         "Relier vers un Panel pour contrôler."],
 pieges=["Utiliser Gate Or : toutes les pièces ressortent True.",
         "Bornes strictes alors que l'énoncé dit « inclus »."],
 var=["Exclure une plage avec Gate Not.",
      "Ajouter une troisième condition sur le matériau."],
 gamif="G-06 Niveaux et déblocage", bareme="1 point si les 20 booléens sont exacts."),

dict(id="A-31", titre="Orienter un flux avec une condition", them="A7 · Portes logiques",
 ref="REF-061", niv="Débutant", duree=7, prereq="A-30",
 obj="Utiliser un booléen pour choisir entre deux flux ou filtrer une liste.",
 comp="Stream Filter, Stream Gate, Dispatch, Boolean Toggle",
 enonce="Un Boolean Toggle doit basculer l'affichage entre un cercle et un carré, sans supprimer aucun composant.",
 depart="Un Circle, un Rectangle et un Boolean Toggle.",
 att="Une seule géométrie affichée à la fois, pilotée par le toggle.",
 mode="GeometryTolerance", tol="0,1 mm", nb=4,
 etapes=["Poser Stream Filter (Sets > Tree).",
         "Brancher le cercle sur Stream 0 et le rectangle sur Stream 1.",
         "Brancher le Boolean Toggle sur l'entrée Gate.",
         "Basculer le toggle et vérifier l'alternance."],
 pieges=["Stream Filter attend un entier : le booléen est converti en 0 ou 1.",
         "Confondre Stream Filter (choisit une entrée) et Stream Gate (aiguille vers une sortie)."],
 var=["Piloter trois géométries avec un slider entier.",
      "Reproduire le comportement avec un Dispatch."],
 gamif="G-24 Sons et retours audio", bareme="1 point si l'alternance fonctionne dans les deux sens."),

# ------------------------------------------- A8 Geometrie vectorielle et filaire
dict(id="A-32", titre="Vecteur, amplitude et direction", them="A8 · Géométrie vectorielle et filaire",
 ref="REF-062", niv="Débutant", duree=7, prereq="A-02",
 obj="Distinguer direction et longueur d'un vecteur.",
 comp="Unit X, Unit Y, Unit Z, Vector 2Pt, Amplitude, Vector Display",
 enonce="Construis le vecteur allant du point (0;0;0) au point (30;40;0), puis produis un vecteur de même direction mais de longueur 100.",
 depart="Deux points internalisés.",
 att="Un vecteur de longueur 50 et un vecteur de longueur 100, même direction.",
 mode="GeometryTolerance", tol="0,01", nb=5,
 etapes=["Poser Vector 2Pt avec les deux points : sa longueur vaut 50.",
         "Vérifier avec Vector Length.",
         "Poser Amplitude et régler l'amplitude sur 100.",
         "Afficher les deux vecteurs avec Vector Display pour comparer."],
 pieges=["Confondre Amplitude (impose une longueur) et Multiplication (multiplie la longueur).",
         "Oublier d'activer Unitize sur Vector 2Pt quand on veut une direction pure."],
 var=["Construire le vecteur normal d'un plan.",
      "Additionner deux vecteurs et vérifier la résultante."],
 gamif="G-26 Feedback visuel immédiat", bareme="1 point par vecteur correct."),

dict(id="A-33", titre="Plans de construction", them="A8 · Géométrie vectorielle et filaire",
 ref="REF-062", niv="Débutant", duree=7, prereq="A-32",
 obj="Poser un plan orienté servant de repère à une géométrie.",
 comp="XY Plane, Plane Normal, Construct Plane, Deconstruct Plane",
 enonce="Place un cercle de rayon 20 dans un plan passant par le point (0;0;50) et incliné à 30° autour de l'axe X.",
 depart="Canvas vide.",
 att="Un cercle de rayon 20 dans le plan incliné demandé.",
 mode="GeometryTolerance", tol="0,1 mm", nb=6,
 etapes=["Poser XY Plane et lui donner l'origine (0;0;50) via Construct Point.",
         "Poser Rotate Plane avec un angle de 30° converti en radians (Radians ou saisie 30 avec le composant Degrees).",
         "Poser Circle et brancher le plan sur P et 20 sur R.",
         "Contrôler visuellement l'inclinaison dans la vue Rhino."],
 pieges=["Grasshopper travaille en radians : saisir 30 donne 30 radians.",
         "Confondre l'origine du plan et le centre du cercle quand on décale ensuite."],
 var=["Construire le plan directement avec Construct Plane et deux vecteurs.",
      "Décomposer le plan avec Deconstruct Plane pour lire ses axes."],
 gamif="G-07 Étoiles de performance", bareme="1 point si le cercle respecte position et inclinaison."),

dict(id="A-34", titre="Primitives filaires", them="A8 · Géométrie vectorielle et filaire",
 ref="REF-063", niv="Débutant", duree=8, prereq="A-33",
 obj="Produire les courbes de base et maîtriser leurs paramètres.",
 comp="Line, Circle, Rectangle, Polygon, Arc, Ellipse",
 enonce="Dans le plan XY, construis un hexagone régulier inscrit dans un cercle de rayon 40, et le rectangle circonscrit à ce même cercle.",
 depart="Canvas vide.",
 att="Un hexagone de rayon 40 et un rectangle de 80 × 80.",
 mode="GeometryTolerance", tol="0,1 mm", nb=6,
 etapes=["Poser Polygon avec un plan XY, un rayon de 40 et 6 segments.",
         "Poser Rectangle avec le même plan et deux domaines de -40 à 40.",
         "Utiliser Construct Domain pour produire ces domaines.",
         "Vérifier que le rectangle est tangent au cercle circonscrit."],
 pieges=["Polygon attend un nombre de côtés, pas un nombre de sommets à calculer.",
         "Rectangle attend des domaines centrés, pas une largeur et une hauteur."],
 var=["Ajouter un congé aux angles du rectangle (entrée R).",
      "Construire un polygone étoilé avec Polygon Edge."],
 gamif="G-15 Dessin à compléter", bareme="1 point par courbe correcte."),

dict(id="A-35", titre="Diviser et évaluer une courbe", them="A8 · Géométrie vectorielle et filaire",
 ref="REF-064", niv="Débutant", duree=8, prereq="A-34",
 obj="Répartir des points le long d'une courbe et récupérer les repères locaux.",
 comp="Divide Curve, Divide Length, Evaluate Curve, Curve Frames",
 enonce="Répartis 12 points équidistants le long de la courbe fournie, puis place un cercle de rayon 5 perpendiculaire à la courbe à chacun de ces points.",
 depart="Une courbe libre internalisée.",
 att="12 cercles de rayon 5 perpendiculaires à la courbe.",
 mode="GeometryTolerance", tol="0,1 mm", nb=5,
 etapes=["Poser Divide Curve avec Count = 11 pour obtenir 12 points (12 divisions donneraient 13 points).",
         "Récupérer la sortie T (tangentes) ou utiliser la sortie P de Perp Frames.",
         "Poser Perp Frames avec Count = 11 : les plans sont déjà perpendiculaires.",
         "Poser Circle avec ces plans et un rayon de 5."],
 pieges=["Divide Curve avec N divisions produit N+1 points quand la courbe est ouverte.",
         "Sur une courbe fermée, N divisions produisent N points."],
 var=["Remplacer Divide Curve par Divide Length pour un pas fixe.",
      "Lofter les 12 cercles pour obtenir un tube."],
 gamif="G-02 Barre de progression", bareme="1 point si 12 cercles perpendiculaires sont produits."),

dict(id="A-36", titre="Courbes passant par des points", them="A8 · Géométrie vectorielle et filaire",
 ref="REF-063", niv="Débutant", duree=7, prereq="A-35",
 obj="Distinguer courbe interpolée et courbe de contrôle.",
 comp="Interpolate, Nurbs Curve, PolyLine, Kink Fillet",
 enonce="À partir des 6 points fournis, trace la courbe qui passe exactement par tous les points, puis celle qui les utilise comme points de contrôle. Superpose les deux.",
 depart="Une liste de 6 points internalisée.",
 att="Deux courbes distinctes sur les mêmes points.",
 mode="GeometryTolerance", tol="0,1 mm", nb=4,
 etapes=["Poser Interpolate (Curve > Spline) : la courbe passe par les points.",
         "Poser Nurbs Curve sur la même liste : les points deviennent des points de contrôle.",
         "Comparer visuellement les deux tracés.",
         "Faire varier le degré des deux courbes pour observer l'effet."],
 pieges=["Attendre que Nurbs Curve passe par les points.",
         "Degré supérieur au nombre de points moins un : la courbe échoue."],
 var=["Fermer les deux courbes et comparer la continuité.",
      "Tracer la PolyLine et arrondir ses angles."],
 gamif="G-12 Memory", bareme="1 point par courbe correcte."),

# -------------------------------------------------------- A9 Transformations
dict(id="A-37", titre="Déplacer par un vecteur", them="A9 · Transformations et réseaux",
 ref="REF-067", niv="Débutant", duree=5, prereq="A-32",
 obj="Appliquer une translation et comprendre que la transformation conserve l'original.",
 comp="Move, Unit Z, Multiplication, Vector 2Pt",
 enonce="Déplace le cercle fourni de 120 mm vers le haut, puis produis 5 copies échelonnées tous les 24 mm sans utiliser de composant de réseau.",
 depart="Un cercle internalisé dans le plan XY.",
 att="6 cercles superposés espacés de 24 mm.",
 mode="GeometryTolerance", tol="0,1 mm", nb=4,
 etapes=["Poser Series avec Start = 0, Step = 24, Count = 6.",
         "Poser Unit Z et brancher la série sur son entrée Factor.",
         "Poser Move : cercle sur G, liste de vecteurs sur T.",
         "Le composant produit 6 cercles : une liste de vecteurs génère une liste de résultats."],
 pieges=["Brancher un seul vecteur et attendre plusieurs copies.",
         "Oublier que la géométrie d'origine reste visible en plus des copies."],
 var=["Décaler selon un vecteur oblique.",
      "Faire varier le rayon en même temps que la hauteur."],
 gamif="G-25 Animation de la solution", bareme="1 point si 6 cercles espacés de 24 mm sont produits."),

dict(id="A-38", titre="Rotation et symétrie", them="A9 · Transformations et réseaux",
 ref="REF-067", niv="Débutant", duree=7, prereq="A-37",
 obj="Tourner et refléter une géométrie autour d'un repère choisi.",
 comp="Rotate, Mirror, Radians, XZ Plane",
 enonce="Fais tourner le profil fourni de 45° autour de l'axe Z passant par l'origine, puis produis son symétrique par rapport au plan XZ.",
 depart="Un profil fermé internalisé.",
 att="Le profil tourné et son symétrique.",
 mode="GeometryTolerance", tol="0,1 mm", nb=5,
 etapes=["Poser Rotate : profil sur G, angle sur A, plan XY sur P.",
         "Convertir 45° en radians avec Radians, ou saisir directement 45 dans un slider réglé en degrés puis convertir.",
         "Poser Mirror : résultat sur G, XZ Plane sur P.",
         "Vérifier la position des deux résultats."],
 pieges=["Saisir 45 sans conversion : la rotation vaut 45 radians.",
         "Le plan de symétrie de Mirror est un plan, pas un axe."],
 var=["Enchaîner rotation et symétrie et comparer avec l'ordre inverse.",
      "Utiliser Rotate Axis pour tourner autour d'un axe quelconque."],
 gamif="G-14 Puzzle de câblage", bareme="1 point par transformation correcte."),

dict(id="A-39", titre="Réseaux rectangulaire et polaire", them="A9 · Transformations et réseaux",
 ref="REF-068", niv="Débutant", duree=8, prereq="A-38",
 obj="Produire une matrice régulière d'objets et lire la structure de données obtenue.",
 comp="Rectangular Array, Polar Array, Param Viewer",
 enonce="Produis une trame de 5 × 4 cellules espacées de 600 mm en X et 400 mm en Y, puis une couronne de 12 copies réparties sur 360°.",
 depart="Un module rectangulaire internalisé.",
 att="20 modules en trame et 12 modules en couronne.",
 mode="GeometryTolerance", tol="0,5 mm", nb=6,
 etapes=["Poser Rectangular Array avec Nx = 5, Ny = 4.",
         "Régler la cellule via un Construct Plane ou en réglant les entrées Sx et Sy sur 600 et 400.",
         "Poser Polar Array avec Count = 12 et Angle = 2π.",
         "Brancher un Param Viewer pour observer l'arbre à deux niveaux produit par le réseau rectangulaire."],
 pieges=["Le réseau rectangulaire produit un arbre, pas une liste plate.",
         "Polar Array attend un angle en radians."],
 var=["Faire varier la taille des modules selon leur position.",
      "Combiner les deux réseaux."],
 gamif="G-10 Coffre à butin", bareme="1 point par réseau correct."),

dict(id="A-40", titre="Mise à l'échelle", them="A9 · Transformations et réseaux",
 ref="REF-067", niv="Débutant", duree=6, prereq="A-39",
 obj="Distinguer l'échelle uniforme et l'échelle non uniforme et maîtriser le centre.",
 comp="Scale, Scale NU, Area, Bounding Box",
 enonce="Réduis le profil à 60 % de sa taille en conservant son centre de gravité, puis produis une version étirée deux fois plus haute sans modifier sa largeur.",
 depart="Un profil fermé internalisé.",
 att="Un profil réduit centré et un profil étiré verticalement.",
 mode="GeometryTolerance", tol="0,1 mm", nb=5,
 etapes=["Poser Area sur le profil pour récupérer son centroïde.",
         "Poser Scale : centre = centroïde, facteur = 0,6.",
         "Poser Scale NU avec X = 1, Y = 1, Z = 2 (ou Y = 2 selon l'orientation).",
         "Comparer les deux résultats."],
 pieges=["Scale utilise par défaut l'origine du repère, pas le centre de l'objet.",
         "Scale NU s'applique selon les axes du plan fourni."],
 var=["Mettre à l'échelle une liste d'objets avec des facteurs différents.",
      "Utiliser Bounding Box pour recadrer avant mise à l'échelle."],
 gamif="G-04 Système de vies", bareme="1 point par mise à l'échelle correcte."),

# ---------------------------------------------------- A10 Surfaces et solides
dict(id="A-41", titre="Extrusion et surface réglée", them="A10 · Surfaces et solides",
 ref="REF-069", niv="Débutant", duree=8, prereq="A-34",
 obj="Passer d'une courbe à une surface par les deux voies les plus courantes.",
 comp="Extrude, Loft, Unit Z, Ruled Surface",
 enonce="Le fichier contient deux profils fermés superposés. Produis la surface qui les relie, puis extrude le profil du bas de 200 mm vers le haut. Compare les deux résultats.",
 depart="Deux profils fermés internalisés à 0 et 300 mm.",
 att="Une surface loftée et une surface extrudée.",
 mode="GeometryTolerance", tol="0,5 mm", nb=5,
 etapes=["Poser Loft et brancher les deux profils dans l'ordre bas puis haut.",
         "Régler les options de Loft (Normal, Straight) via son menu contextuel.",
         "Poser Extrude avec Unit Z multiplié par 200.",
         "Comparer : Loft suit les deux profils, Extrude conserve la section constante."],
 pieges=["Profils branchés dans le désordre : le Loft se vrille.",
         "Extrude attend un vecteur, pas une distance."],
 var=["Lofter trois profils et observer la continuité.",
      "Extruder le long d'une courbe avec Extrude Along."],
 gamif="G-27 Narration Serengeti", bareme="1 point par surface correcte."),

dict(id="A-42", titre="Balayage et révolution", them="A10 · Surfaces et solides",
 ref="REF-069", niv="Débutant", duree=8, prereq="A-41",
 obj="Générer une surface par déplacement d'un profil le long d'un rail ou autour d'un axe.",
 comp="Sweep 1, Sweep 2, Revolution, Rail",
 enonce="Balaie le profil circulaire fourni le long de la courbe guide pour obtenir un tube, puis produis un vase par révolution du profil plan autour de l'axe Z.",
 depart="Un profil circulaire, une courbe guide et un profil plan internalisés.",
 att="Un tube et une surface de révolution.",
 mode="GeometryTolerance", tol="0,5 mm", nb=6,
 etapes=["Poser Sweep 1 : courbe guide sur Rail, profil sur Sections.",
         "Si le profil n'est pas positionné sur le rail, l'orienter d'abord avec Orient ou Perp Frame.",
         "Poser Revolution : profil plan sur P, axe Z sur A, domaine 0 à 2π sur D.",
         "Contrôler la fermeture des surfaces obtenues."],
 pieges=["Profil non perpendiculaire au rail : le balayage se déforme.",
         "Domaine de révolution incomplet : le vase reste ouvert."],
 var=["Balayer avec deux rails (Sweep 2).",
      "Faire varier la section le long du rail."],
 gamif="G-05 Badges et trophées", bareme="1 point par surface correcte."),

dict(id="A-43", titre="Fermer une polysurface en solide", them="A10 · Surfaces et solides",
 ref="REF-070", niv="Débutant", duree=7, prereq="A-41",
 obj="Obtenir un solide fermé et savoir le vérifier.",
 comp="Cap Holes, Brep Join, Is Solid (Brep Wireframe / Volume)",
 enonce="La polysurface fournie comporte deux ouvertures. Ferme-la et prouve dans un Panel qu'elle est bien un solide.",
 depart="Une polysurface ouverte internalisée.",
 att="Un Panel affichant True pour le caractère solide, et un volume non nul.",
 mode="SingleValue", tol="—", nb=4,
 etapes=["Poser Cap Holes sur la polysurface.",
         "Poser Volume : un volume non nul confirme la fermeture.",
         "Utiliser Deconstruct Brep ou un composant Is Solid pour obtenir directement le booléen.",
         "Relier vers un Panel."],
 pieges=["Cap Holes ne ferme que les ouvertures planes.",
         "Un volume affiché à zéro signale une polysurface encore ouverte."],
 var=["Réparer une ouverture non plane avec un Loft complémentaire puis Brep Join.",
      "Contrôler l'étanchéité en vue de l'impression 3D."],
 gamif="G-20 Erreur volontaire à débusquer", bareme="1 point si le solide est fermé et prouvé."),

dict(id="A-44", titre="Opérations booléennes", them="A10 · Surfaces et solides",
 ref="REF-071", niv="Débutant", duree=8, prereq="A-43",
 obj="Combiner des solides et contrôler l'ordre des opérandes.",
 comp="Solid Union, Solid Difference, Solid Intersection",
 enonce="Perce le bloc fourni de quatre trous cylindriques de 20 mm de diamètre traversants, puis calcule le volume de matière retirée.",
 depart="Un bloc et quatre cylindres internalisés.",
 att="Le bloc percé et un Panel affichant le volume retiré.",
 mode="NumericTolerance", tol="1 %", nb=6,
 etapes=["Poser Solid Difference : bloc sur A, cylindres sur B.",
         "Vérifier que les cylindres traversent bien le bloc.",
         "Calculer le Volume du bloc initial et du bloc percé.",
         "Soustraire les deux valeurs et afficher le résultat."],
 pieges=["Inverser A et B : on obtient les cylindres percés par le bloc.",
         "Cylindres tangents à la face : l'opération échoue."],
 var=["Additionner les volumes des cylindres et comparer au volume retiré.",
      "Remplacer la différence par une intersection."],
 gamif="G-21 Golf de composants", bareme="1 point pour le perçage, 1 point pour le volume."),

dict(id="A-45", titre="Intersections entre géométries", them="A10 · Surfaces et solides",
 ref="REF-071", niv="Débutant", duree=7, prereq="A-44",
 obj="Extraire les points, courbes ou surfaces d'intersection entre objets.",
 comp="Curve | Curve, Brep | Plane, Brep | Brep, Curve | Brep",
 enonce="Coupe le solide fourni par un plan horizontal à mi-hauteur et récupère le contour de coupe. Indique sa longueur totale.",
 depart="Un solide internalisé.",
 att="Le contour de coupe et un Panel affichant sa longueur développée.",
 mode="NumericTolerance", tol="0,5 %", nb=6,
 etapes=["Poser Bounding Box puis Deconstruct Box pour obtenir la hauteur.",
         "Construire le plan de coupe à mi-hauteur avec XY Plane et Construct Point.",
         "Poser Brep | Plane et récupérer la sortie C (courbes).",
         "Poser Length et Mass Addition pour la longueur totale."],
 pieges=["Plan de coupe placé hors du solide : aucune courbe produite.",
         "Plusieurs contours produits : additionner toutes les longueurs."],
 var=["Produire une série de coupes régulières pour un plan de fabrication.",
      "Intersecter deux solides et récupérer la courbe commune."],
 gamif="G-16 Chasse au trésor", bareme="1 point pour le contour, 1 point pour la longueur."),

dict(id="A-46", titre="Détecter une collision", them="A10 · Surfaces et solides",
 ref="REF-072", niv="Débutant", duree=7, prereq="A-45",
 obj="Identifier les objets en interférence dans un ensemble.",
 comp="Collision One|Many, Graft, Flatten Tree, Dispatch, Custom Preview, Colour Swatch",
 enonce="Parmi les 15 blocs disposés, identifie ceux qui entrent en collision avec le volume de gabarit fourni et affiche-les en rouge.",
 depart="15 blocs et un volume de gabarit internalisés.",
 att="Les 9 blocs en collision, isolés par Dispatch et affichés en rouge.",
 mode="SetEquality", tol="—", nb=7,
 etapes=["Poser Collision One|Many, mais en inversant les rôles attendus : les blocs sur Collider, le gabarit sur Obstacles.",
         "Grafter l'entrée Collider : chaque bloc se retrouve seul dans sa branche.",
         "La sortie Collision donne alors un booléen PAR BLOC ; aplatir le résultat avec Flatten Tree.",
         "Poser Dispatch : les blocs sur List, les booléens sur Pattern.",
         "Afficher la sortie A avec un Custom Preview alimenté par un Colour Swatch rouge."],
 pieges=["Brancher le gabarit sur Collider et les blocs sur Obstacles sans grafter : le composant ne renvoie alors qu'un SEUL booléen global et l'index du PREMIER bloc touché, pas la liste complète. C'est le piège central de cet exercice.",
         "Confondre la sortie Collision (booléens) et la sortie Index.",
         "Collision One|Many ne détecte pas le simple contact tangent.",
         "Croire que Collision Many|Many convient : ce composant n'a qu'une entrée et teste un ensemble contre lui-même."],
 var=["Compter les collisions avec Mass Addition.",
      "Décaler automatiquement les blocs en collision."],
 gamif="G-01 Score visible", bareme="1 point si les bons blocs sont identifiés."),

# ---------------------------------------------------------------- A11 Mesures
dict(id="A-47", titre="Longueur, aire et volume", them="A11 · Mesures géométriques",
 ref="REF-079", niv="Débutant", duree=6, prereq="A-43",
 obj="Mesurer les trois grandeurs de base et repérer le composant adapté à chaque type.",
 comp="Length, Area, Volume, Mass Addition",
 enonce="Pour l'assemblage fourni, affiche dans un même Panel le développé total des arêtes, la surface développée et le volume, dans cet ordre.",
 depart="Un solide internalisé.",
 att="Un Panel de trois valeurs.",
 mode="NumericTolerance", tol="0,5 %", nb=7,
 etapes=["Poser Deconstruct Brep pour obtenir arêtes et faces.",
         "Poser Length sur les arêtes puis Mass Addition.",
         "Poser Area sur les faces puis Mass Addition, ou Area directement sur le Brep.",
         "Poser Volume sur le Brep et assembler les trois valeurs avec Merge."],
 pieges=["Area sur un Brep fermé renvoie la surface totale : inutile de sommer les faces.",
         "Volume nul sur une polysurface ouverte."],
 var=["Convertir les unités en m² et m³.",
      "Comparer avec les valeurs affichées par la commande Rhino."],
 gamif="G-29 Défi quotidien", bareme="1 point si les trois valeurs sont dans la tolérance."),

dict(id="A-48", titre="Courbure et point le plus proche", them="A11 · Mesures géométriques",
 ref="REF-080", niv="Débutant", duree=7, prereq="A-35",
 obj="Analyser localement une courbe et localiser un point de référence.",
 comp="Curvature, Curve Closest Point, Evaluate Curve, Graph Mapper",
 enonce="Sur la courbe fournie, identifie le point de courbure maximale et indique son rayon de courbure.",
 depart="Une courbe libre internalisée.",
 att="Un point marqué sur la courbe et un Panel affichant le rayon de courbure.",
 mode="NumericTolerance", tol="1 %", nb=7,
 etapes=["Poser Divide Curve avec 200 divisions pour échantillonner finement.",
         "Poser Curvature sur ces paramètres : la sortie K donne le vecteur de courbure.",
         "Poser Vector Length puis Sort List pour trouver la valeur maximale.",
         "Le rayon vaut l'inverse de la courbure : poser Division avec 1 sur A."],
 pieges=["Courbure nulle sur un segment droit : la division par zéro produit une valeur infinie.",
         "Échantillonnage trop grossier : le maximum réel est manqué."],
 var=["Colorer la courbe selon sa courbure avec Gradient.",
      "Détecter les points d'inflexion."],
 gamif="G-28 Avatar et personnalisation", bareme="1 point pour le point, 1 point pour le rayon."),

dict(id="A-49", titre="Centre de gravité", them="A11 · Mesures géométriques",
 ref="REF-081", niv="Débutant", duree=6, prereq="A-47",
 obj="Obtenir le centroïde d'une surface ou d'un volume et l'utiliser comme repère.",
 comp="Area, Volume, Point, Text Tag 3D",
 enonce="Calcule le centre de gravité de chacune des 6 pièces fournies et affiche à cet endroit le numéro de la pièce.",
 depart="6 solides internalisés.",
 att="6 étiquettes numérotées placées aux centroïdes.",
 mode="GeometryTolerance", tol="0,5 mm", nb=5,
 etapes=["Poser Volume sur la liste des solides : la sortie C donne les centroïdes.",
         "Poser Series pour produire les numéros de 1 à 6.",
         "Formater les numéros avec Format si un affichage sur deux chiffres est souhaité.",
         "Poser Text Tag 3D avec les centroïdes en L et les textes en T."],
 pieges=["Area donne le centroïde surfacique, Volume le centroïde volumique : ils diffèrent.",
         "Text Tag 3D n'apparaît qu'en aperçu, il ne se cuit qu'avec un Bake explicite."],
 var=["Trier les pièces par masse en pondérant par la densité.",
      "Placer un repère orienté au centroïde."],
 gamif="G-05 Badges et trophées", bareme="1 point si les 6 étiquettes sont bien placées."),
]
